// ⚠ このファイルは自動生成物。手で編集しない。
// 生成: node scripts/gen-emoji-shortcodes.mjs
// 素: emoji-picker-react の dist/data/emojis-en.json（内部パス。理由は生成スクリプトのコメント参照）
//
// `:` ショートコード補完（#190）の辞書。1件 = [絵文字, ショートコード, 検索用キーワード]。
// ショートコードは Unicode の正式名を snake_case にしたもので、**Slack / GitHub の綴りとは
// 一致しないものがある**。ただし確定時に本文へ入るのは絵文字そのもの（ショートコード文字列は
// 残らない）ため、綴りの違いが送信結果に出ることはない — ここはあくまで検索キー。

export type EmojiShortcodeEntry = readonly [emoji: string, shortcode: string, keywords: string];

export const EMOJI_SHORTCODES: readonly EmojiShortcodeEntry[] = [
  ['🥇', '1st_place_medal', 'gold first'],
  ['🥈', '2nd_place_medal', 'second silver'],
  ['🥉', '3rd_place_medal', 'third bronze'],
  ['🅰️', 'a_button_blood_type', 'a button (blood type)'],
  ['🆎', 'ab_button_blood_type', 'ab button (blood type)'],
  ['🧮', 'abacus', 'calculation'],
  ['🧑‍🎤', 'actor', 'rock star singer entertainer'],
  ['🩹', 'adhesive_bandage', ''],
  ['🎟️', 'admission_tickets', ''],
  ['👨', 'adult', 'man'],
  ['🚡', 'aerial_tramway', 'car cable gondola'],
  ['✈️', 'airplane', 'aeroplane'],
  ['🛬', 'airplane_arrival', 'landing arrivals arriving aeroplane'],
  ['⏰', 'alarm_clock', ''],
  ['⚗️', 'alembic', 'tool chemistry'],
  ['👽', 'alien', 'ufo face fantasy creature extraterrestrial'],
  ['👾', 'alien_monster', 'ufo face creature extraterrestrial'],
  ['🚑', 'ambulance', 'vehicle'],
  ['🏈', 'american_football', ''],
  ['🦠', 'amoeba', 'virus microbe bacteria'],
  ['🫀', 'anatomical_heart', 'organ pulse cardiology'],
  ['⚓', 'anchor', 'ship tool'],
  ['💢', 'anger_symbol', 'mad angry comic'],
  ['😠', 'angry_face', 'mad anger'],
  ['👿', 'angry_face_with_horns', 'imp demon devil fantasy'],
  ['😧', 'anguished_face', ''],
  ['🐜', 'ant', 'insect'],
  ['📶', 'antenna_bars', 'cell phone mobile'],
  ['😰', 'anxious_face_with_sweat', 'blue cold rushed'],
  ['🦧', 'ape', 'orangutan'],
  ['♒', 'aquarius', 'water bearer zodiac'],
  ['♐', 'archer', 'zodiac sagittarius'],
  ['🚛', 'articulated_lorry', 'semi truck'],
  ['🧑‍🎨', 'artist', 'palette'],
  ['🎨', 'artist_palette', 'museum painting'],
  ['🫏', 'ass', 'mule burro donkey animal mammal stubborn'],
  ['😲', 'astonished_face', 'shocked totally'],
  ['🧑‍🚀', 'astronaut', 'rocket'],
  ['🏧', 'atm_sign', 'bank teller automated'],
  ['⚛️', 'atom_symbol', 'atheist'],
  ['🚗', 'automobile', 'car'],
  ['🥑', 'avocado', 'food fruit'],
  ['🪓', 'axe', 'chop wood split hatchet'],
  ['🅱️', 'b_button_blood_type', 'b button (blood type)'],
  ['👼', 'baby_angel', 'face fantasy fairy tale'],
  ['🍼', 'baby_bottle', 'milk drink'],
  ['🐤', 'baby_chick', 'bird'],
  ['🚼', 'baby_symbol', 'changing'],
  ['🔙', 'back_arrow', ''],
  ['👇', 'backhand_index_pointing_down', 'finger'],
  ['👈', 'backhand_index_pointing_left', 'finger'],
  ['👉', 'backhand_index_pointing_right', 'finger'],
  ['👆', 'backhand_index_pointing_up', 'finger'],
  ['🥓', 'bacon', 'food meat breakfast'],
  ['🥯', 'bagel', 'bakery schmear breakfast'],
  ['🛄', 'baggage_claim', ''],
  ['🥖', 'baguette_bread', 'food french'],
  ['⚖️', 'balance_scale', 'libra zodiac justice'],
  ['🩰', 'ballet_shoes', 'dance'],
  ['🎈', 'balloon', 'celebration'],
  ['🗳️', 'ballot_box_with_ballot', ''],
  ['🖊️', 'ballpoint', 'pen'],
  ['🍌', 'banana', 'fruit'],
  ['🪕', 'banjo', 'music stringed'],
  ['🏦', 'bank', 'building'],
  ['📊', 'bar_chart', 'graph'],
  ['💈', 'barber_pole', 'haircut'],
  ['🚧', 'barrier', 'construction'],
  ['⚾', 'baseball', ''],
  ['🧺', 'basket', 'picnic farming laundry'],
  ['🛁', 'bath', 'bathtub'],
  ['🩳', 'bathing_suit', 'pants shorts underwear'],
  ['🔋', 'battery', ''],
  ['🏖️', 'beach_with_umbrella', ''],
  ['😁', 'beaming_face_with_smiling_eyes', 'grin smile'],
  ['🐻', 'bear', 'face'],
  ['💓', 'beating_heart', 'heartbeat pulsating'],
  ['🛏️', 'bed', 'hotel sleep'],
  ['🐝', 'bee', 'insect honeybee'],
  ['🍺', 'beer_mug', 'bar drink'],
  ['🔔', 'bell', ''],
  ['🫑', 'bell_pepper', 'capsicum vegetable'],
  ['🔕', 'bell_with_slash', 'mute quiet silent forbidden'],
  ['🛎️', 'bellhop_bell', 'hotel'],
  ['🍱', 'bento_box', ''],
  ['🍒', 'berries', 'red fruit cherry cherries'],
  ['🧃', 'beverage_box', 'juice straw sweet'],
  ['🚲', 'bike', 'bicycle'],
  ['👙', 'bikini', 'swim clothing'],
  ['🫐', 'bilberry', 'blue blueberry blueberries'],
  ['🧢', 'billed_cap', 'baseball cap'],
  ['☣️', 'biohazard', 'sign'],
  ['🐦', 'bird', ''],
  ['🏸', 'birdie', 'game racquet badminton shuttlecock'],
  ['🎂', 'birthday_cake', 'sweet pastry dessert celebration'],
  ['🫦', 'biting_lip', 'fear anxious nervous worried flirting uncomfortable'],
  ['🐦‍⬛', 'black_bird', 'crow rook raven'],
  ['🐈‍⬛', 'black_cat', 'unlucky'],
  ['⚫', 'black_circle', 'geometric'],
  ['🏴', 'black_flag', 'waving'],
  ['🖤', 'black_heart', 'evil wicked'],
  ['⬛', 'black_large_square', 'geometric'],
  ['◾', 'black_medium_small_square', 'geometric'],
  ['◼️', 'black_medium_square', 'geometric'],
  ['✒️', 'black_nib', 'pen'],
  ['▪️', 'black_small_square', 'geometric'],
  ['🔲', 'black_square_button', 'geometric'],
  ['🌼', 'blossom', 'flower'],
  ['🐡', 'blowfish', ''],
  ['📀', 'blu_ray', 'dvd disk optical computer'],
  ['📘', 'blue_book', ''],
  ['🔵', 'blue_circle', 'geometric'],
  ['💙', 'blue_heart', ''],
  ['🟦', 'blue_square', ''],
  ['🐗', 'boar', 'pig'],
  ['🛹', 'board', 'skateboard'],
  ['👅', 'body', 'tongue'],
  ['🥬', 'bok_choy', 'kale cabbage lettuce leafy green'],
  ['💣', 'bomb', 'comic'],
  ['🔖', 'bookmark', ''],
  ['📑', 'bookmark_tabs', 'marker'],
  ['📚', 'books', ''],
  ['💥', 'boom', 'comic collision'],
  ['🍾', 'bottle_with_popping_cork', 'bar drink'],
  ['💐', 'bouquet', 'flower'],
  ['🏹', 'bow_and_arrow', 'archer zodiac sagittarius'],
  ['🥣', 'bowl_with_spoon', 'cereal congee breakfast'],
  ['🎳', 'bowling', 'ball game'],
  ['🥊', 'boxing_glove', ''],
  ['🧠', 'brain', 'intelligent'],
  ['🤱', 'breast_feeding', 'baby nursing'],
  ['🌉', 'bridge_at_night', ''],
  ['💼', 'briefcase', ''],
  ['🔆', 'bright_button', 'brightness'],
  ['⛓️‍💥', 'broken_chain', 'break cuffs freedom breaking'],
  ['💔', 'broken_heart', 'break'],
  ['🧹', 'broom', 'witch cleaning sweeping'],
  ['🟤', 'brown_circle', ''],
  ['🤎', 'brown_heart', ''],
  ['🍄‍🟫', 'brown_mushroom', 'food fungus nature vegetable'],
  ['🟫', 'brown_square', ''],
  ['🪥', 'brush', 'clean teeth dental hygiene bathroom toothbrush'],
  ['🧋', 'bubble_tea', 'milk pearl'],
  ['🐛', 'bug', 'insect'],
  ['🏨', 'building', 'hotel'],
  ['🏗️', 'building_construction', ''],
  ['🚅', 'bullet_train', 'speed railway shinkansen'],
  ['🐇', 'bunny', 'pet rabbit'],
  ['🍔', 'burger', 'hamburger'],
  ['🫧', 'burp', 'soap clean bubbles underwater'],
  ['🚌', 'bus', 'vehicle'],
  ['🚏', 'bus_stop', ''],
  ['👤', 'bust_in_silhouette', ''],
  ['👥', 'busts_in_silhouette', ''],
  ['©️', 'c', 'copyright'],
  ['🌵', 'cactus', 'plant'],
  ['🤙', 'call_me_hand', 'shaka hang loose'],
  ['📷', 'camera', 'video'],
  ['📸', 'camera_with_flash', 'video'],
  ['🏕️', 'camping', ''],
  ['✖️', 'cancel', 'x × sign multiply multiplication'],
  ['🕯️', 'candle', 'light'],
  ['🍬', 'candy', 'sweet dessert'],
  ['🥫', 'canned_food', ''],
  ['🛶', 'canoe', 'boat'],
  ['🗃️', 'card_file_box', ''],
  ['📇', 'card_index', 'rolodex'],
  ['🗂️', 'card_index_dividers', ''],
  ['🎠', 'carousel_horse', ''],
  ['🎏', 'carp_streamer', 'celebration'],
  ['🪚', 'carpentry_saw', 'tool lumber carpenter'],
  ['🥕', 'carrot', 'food vegetable'],
  ['🏰', 'castle', 'european'],
  ['🐱', 'cat_face', 'pet'],
  ['😹', 'cat_with_tears_of_joy', 'face'],
  ['😼', 'cat_with_wry_smile', 'face ironic'],
  ['⛓️', 'chains', ''],
  ['💒', 'chapel', 'wedding romance'],
  ['📉', 'chart_decreasing', 'down graph trend'],
  ['📈', 'chart_increasing', 'graph trend growth upward'],
  ['💹', 'chart_increasing_with_yen', 'graph money growth'],
  ['☑️', 'check_box_with_check', ''],
  ['🛫', 'check_in', 'airplane aeroplane departure departures airplane departure'],
  ['✔️', 'check_mark', ''],
  ['✅', 'check_mark_button', ''],
  ['🧀', 'cheese_wedge', ''],
  ['🏁', 'chequered_flag', 'racing checkered'],
  ['🌸', 'cherry_blossom', 'flower'],
  ['♟️', 'chess_pawn', 'dupe expendable'],
  ['🧰', 'chest', 'tool toolbox mechanic'],
  ['🌰', 'chestnut', 'plant'],
  ['🐔', 'chicken', 'bird'],
  ['🧆', 'chickpea', 'falafel meatball'],
  ['🚸', 'children_crossing', 'traffic pedestrian'],
  ['🐿️', 'chipmunk', 'squirrel'],
  ['🍫', 'chocolate_bar', 'sweet dessert'],
  ['🎄', 'christmas_tree', 'celebration'],
  ['⛪', 'church', 'cross religion christian'],
  ['🚬', 'cigarette', 'smoking'],
  ['Ⓜ️', 'circled_m', ''],
  ['🎪', 'circus_tent', ''],
  ['🏙️', 'cityscape', ''],
  ['🌆', 'cityscape_at_dusk', 'sunset evening landscape'],
  ['🆑', 'cl_button', ''],
  ['🎬', 'clapper_board', 'movie'],
  ['👏', 'clapping_hands', ''],
  ['🏛️', 'classical_building', ''],
  ['🦞', 'claws', 'bisque lobster seafood'],
  ['🧱', 'clay', 'wall brick bricks mortar'],
  ['🍻', 'clinking_beer_mugs', 'bar drink'],
  ['🥂', 'clinking_glasses', 'drink celebrate'],
  ['📋', 'clipboard', ''],
  ['🔃', 'clockwise_vertical_arrows', 'reload'],
  ['📕', 'closed_book', ''],
  ['📪', 'closed_mailbox_with_lowered_flag', 'postbox'],
  ['📫', 'closed_mailbox_with_raised_flag', 'postbox'],
  ['🌂', 'closed_umbrella', 'rain clothing'],
  ['🌩️', 'cloud_with_lightning', ''],
  ['⛈️', 'cloud_with_lightning_and_rain', 'thunder'],
  ['🌧️', 'cloud_with_rain', ''],
  ['🌨️', 'cloud_with_snow', 'cold'],
  ['🤡', 'clown_face', ''],
  ['♣️', 'club_suit', 'card game'],
  ['👝', 'clutch_bag', 'pouch clothing'],
  ['🧥', 'coat', 'jacket'],
  ['🍸', 'cocktail_glass', 'bar drink'],
  ['🧑‍💻', 'coder', 'inventor software developer technologist'],
  ['⚰️', 'coffin', 'death'],
  ['⚙️', 'cog', 'gear tool cogwheel'],
  ['👛', 'coin', 'purse clothing'],
  ['🥶', 'cold_face', 'icicles freezing frostbite blue faced'],
  ['☄️', 'comet', 'space'],
  ['🧭', 'compass', 'magnetic navigation orienteering'],
  ['💽', 'computer_disk', 'optical minidisk'],
  ['🖱️', 'computer_mouse', ''],
  ['🎊', 'confetti_ball', 'celebration'],
  ['😖', 'confounded_face', ''],
  ['😕', 'confused_face', 'meh'],
  ['👷', 'construction_worker', 'hat'],
  ['🎛️', 'control_knobs', 'music'],
  ['🏪', 'convenience_store', ''],
  ['🧑‍🍳', 'cook', 'chef'],
  ['🍚', 'cooked_rice', ''],
  ['🍪', 'cookie', 'sweet dessert'],
  ['🆒', 'cool_button', ''],
  ['🛋️', 'couch_and_lamp', 'hotel'],
  ['🔄', 'counterclockwise_arrows_button', 'withershins anticlockwise'],
  ['💑', 'couple_with_heart', 'love'],
  ['👨‍❤️‍👨', 'couple_with_heart_man_man', 'love'],
  ['👩‍❤️‍👨', 'couple_with_heart_woman_man', 'love'],
  ['👩‍❤️‍👩', 'couple_with_heart_woman_woman', 'love'],
  ['🐄', 'cow', ''],
  ['🐮', 'cow_face', ''],
  ['🤠', 'cowboy_hat_face', 'cowgirl'],
  ['🥞', 'cr_pe', 'food hotcake pancake pancakes breakfast'],
  ['🦀', 'crab', 'cancer zodiac'],
  ['🖍️', 'crayon', ''],
  ['💳', 'credit_card', 'money'],
  ['🌙', 'crescent_moon', ''],
  ['🦗', 'cricket', 'grasshopper'],
  ['🏏', 'cricket_game', 'bat ball'],
  ['🐊', 'crocodile', ''],
  ['❌', 'cross_mark', 'x cancel multiply multiplication'],
  ['❎', 'cross_mark_button', 'x square'],
  ['🤞', 'crossed_fingers', 'hand luck'],
  ['🎌', 'crossed_flags', 'japanese celebration'],
  ['⚔️', 'crossed_swords', 'weapon'],
  ['😿', 'crying_cat', 'sad face tear'],
  ['😢', 'crying_face', 'sad tear'],
  ['🔮', 'crystal_ball', 'tool fantasy fortune fairy tale'],
  ['🥤', 'cup_with_straw', 'soda juice'],
  ['🧁', 'cupcake', 'sweet bakery'],
  ['🥌', 'curling_stone', 'game rock'],
  ['➰', 'curly_loop', ''],
  ['💱', 'currency_exchange', 'bank money'],
  ['🍛', 'curry_rice', ''],
  ['🍮', 'custard', 'sweet dessert pudding'],
  ['🛃', 'customs', ''],
  ['🥩', 'cut_of_meat', 'chop steak lambchop porkchop'],
  ['✂️', 'cutting', 'tool scissors'],
  ['🌀', 'cyclone', 'dizzy twister typhoon hurricane'],
  ['🗡️', 'dagger', 'knife weapon'],
  ['🧈', 'dairy', 'butter'],
  ['🦫', 'dam', 'beaver'],
  ['🍡', 'dango', 'stick sweet skewer dessert japanese'],
  ['🕶️', 'dark', 'eye eyewear glasses sunglasses'],
  ['💨', 'dashing_away', 'comic running'],
  ['📅', 'date', 'calendar'],
  ['🧏‍♂️', 'deaf_man', ''],
  ['🧏', 'deaf_person', 'ear hear accessibility'],
  ['🧏‍♀️', 'deaf_woman', ''],
  ['🌳', 'deciduous_tree', 'shedding'],
  ['🦌', 'deer', ''],
  ['🚚', 'delivery_truck', ''],
  ['🏬', 'department_store', ''],
  ['🏚️', 'derelict_house', ''],
  ['🏜️', 'desert', ''],
  ['🏝️', 'desert_island', ''],
  ['🖥️', 'desktop_computer', ''],
  ['♦️', 'diamond_suit', 'card game'],
  ['💠', 'diamond_with_a_dot', 'comic inside geometric'],
  ['🔅', 'dim_button', 'low brightness'],
  ['🎯', 'direct_hit', 'dart game target bullseye'],
  ['😞', 'disappointed_face', ''],
  ['🥸', 'disguised_face', 'nose glasses incognito'],
  ['🤿', 'diving_mask', 'scuba snorkeling'],
  ['🪔', 'diya_lamp', 'oil'],
  ['💫', 'dizzy', 'star comic'],
  ['🧬', 'dna', 'gene life genetics biologist evolution'],
  ['🦤', 'dodo', 'large mauritius extinction'],
  ['🐕', 'dog', 'pet'],
  ['🐶', 'dog_face', 'pet'],
  ['💵', 'dollar_banknote', 'bill money currency'],
  ['🐬', 'dolphin', 'flipper'],
  ['🍩', 'donut', 'sweet dessert doughnut breakfast'],
  ['🚪', 'door', ''],
  ['🫥', 'dotted_line_face', 'hide depressed disappear introvert invisible'],
  ['🔯', 'dotted_six_pointed_star', 'fortune'],
  ['➿', 'double_curly_loop', ''],
  ['‼️', 'double_exclamation_mark', 'bangbang'],
  ['🕊️', 'dove', 'fly bird peace'],
  ['⬇️', 'down_arrow', 'south cardinal direction'],
  ['↙️', 'down_left_arrow', 'direction southwest intercardinal'],
  ['↘️', 'down_right_arrow', 'direction southeast intercardinal'],
  ['😓', 'downcast_face_with_sweat', 'cold'],
  ['🔽', 'downwards_button', 'arrow'],
  ['🐲', 'dragon_face', 'fairy tale'],
  ['👗', 'dress', 'clothing'],
  ['🐪', 'dromedary', 'hump camel'],
  ['🤤', 'drooling_face', ''],
  ['🩸', 'drop_of_blood', 'bleed injury medicine menstruation blood donation'],
  ['💧', 'droplet', 'cold comic sweat'],
  ['🥁', 'drumsticks', 'music'],
  ['🦆', 'duck', 'bird'],
  ['🌇', 'dusk', 'sun sunset'],
  ['🧨', 'dynamite', 'explosive fireworks firecracker'],
  ['📧', 'e_mail', 'email letter'],
  ['🦅', 'eagle', 'bird'],
  ['👂', 'ear', 'body'],
  ['🌽', 'ear_of_corn', 'maze maize'],
  ['🦻', 'ear_with_hearing_aid', 'accessibility hard of hearing'],
  ['🎧', 'earbud', 'headphone'],
  ['🥚', 'egg', 'food breakfast'],
  ['🍆', 'eggplant', 'aubergine vegetable'],
  ['🕗', 'eight_o_clock', '8 00 8:00'],
  ['✴️', 'eight_pointed_star', ''],
  ['✳️', 'eight_spoked_asterisk', ''],
  ['🕣', 'eight_thirty', '8 8:30 clock'],
  ['⏏️', 'eject_button', ''],
  ['🔌', 'electric_plug', 'electricity'],
  ['🧑‍🔧', 'electrician', 'plumber mechanic tradesperson'],
  ['🐘', 'elephant', ''],
  ['🕚', 'eleven_o_clock', '00 11 11:00'],
  ['🕦', 'eleven_thirty', '11 11:30 clock'],
  ['🧝', 'elf', 'magical'],
  ['🫎', 'elk', 'moose animal mammal antlers'],
  ['🪹', 'empty_nest', 'nesting'],
  ['🔚', 'end_arrow', ''],
  ['🧑‍🔬', 'engineer', 'chemist scientist biologist physicist'],
  ['😡', 'enraged_face', 'mad red angry pouting'],
  ['🚫', 'entry', 'no not forbidden prohibited'],
  ['✉️', 'envelope', 'email letter'],
  ['📩', 'envelope_with_arrow', 'email e mail outgoing'],
  ['🐎', 'equestrian', 'horse racing racehorse'],
  ['💶', 'euro_banknote', 'bill money currency'],
  ['🌲', 'evergreen_tree', ''],
  ['🧿', 'evil_eye', 'bead charm nazar talisman nazar amulet'],
  ['🐑', 'ewe', 'sheep female'],
  ['⁉️', 'exclamation_question_mark', 'interrobang punctuation'],
  ['😑', 'expressionless_face', 'meh inexpressive unexpressive'],
  ['👁️‍🗨️', 'eye_in_speech_bubble', 'balloon witness'],
  ['🥽', 'eye_protection', 'goggles welding swimming'],
  ['👓', 'eyeglasses', 'eyewear clothing'],
  ['👀', 'eyes', 'face'],
  ['😘', 'face_blowing_a_kiss', ''],
  ['😮‍💨', 'face_exhaling', 'gasp groan exhale relief whisper whistle'],
  ['🥹', 'face_holding_back_tears', 'cry sad angry proud resist'],
  ['😶‍🌫️', 'face_in_the_fog', 'absentminded face in clouds head in clouds'],
  ['😋', 'face_savoring_food', 'yum smile delicious savouring'],
  ['😱', 'face_screaming_in_fear', 'munch scared'],
  ['🤮', 'face_vomiting', 'puke sick'],
  ['😵', 'face_with_crossed_out_eyes', 'dead knocked out'],
  ['🫤', 'face_with_diagonal_mouth', 'meh unsure skeptical disappointed'],
  ['🤭', 'face_with_hand_over_mouth', 'whoops'],
  ['🤕', 'face_with_head_bandage', 'hurt injury'],
  ['😷', 'face_with_medical_mask', 'cold sick doctor'],
  ['🧐', 'face_with_monocle', 'stuffy'],
  [
    '🫢',
    'face_with_open_eyes_and_hand_over_mouth',
    'awe scared surprise amazement disbelief embarrass',
  ],
  ['😮', 'face_with_open_mouth', 'sympathy'],
  ['🫣', 'face_with_peeking_eye', 'peep stare captivated'],
  ['🤨', 'face_with_raised_eyebrow', 'skeptic distrust'],
  ['🙄', 'face_with_rolling_eyes', 'eyeroll'],
  ['😵‍💫', 'face_with_spiral_eyes', 'whoa dizzy trouble hypnotized'],
  ['😤', 'face_with_steam_from_nose', 'won triumph'],
  ['🤬', 'face_with_symbols_on_mouth', 'swearing'],
  ['😂', 'face_with_tears_of_joy', 'laugh'],
  ['🤒', 'face_with_thermometer', 'ill sick'],
  ['😛', 'face_with_tongue', ''],
  ['😶', 'face_without_mouth', 'quiet silent'],
  ['🏭', 'factory', 'building'],
  ['🧑‍🏭', 'factory_worker', 'assembly industrial'],
  ['🧚', 'fairy', 'puck oberon titania'],
  ['💀', 'fairy_tale', 'face skull death monster'],
  ['🍂', 'fallen_leaf', 'falling'],
  ['👪', 'family', ''],
  ['🧑‍🧑‍🧒', 'family_adult_adult_child', ''],
  ['🧑‍🧑‍🧒‍🧒', 'family_adult_adult_child_child', ''],
  ['🧑‍🧒', 'family_adult_child', ''],
  ['🧑‍🧒‍🧒', 'family_adult_child_child', ''],
  ['👨‍👦', 'family_man_boy', ''],
  ['👨‍👦‍👦', 'family_man_boy_boy', ''],
  ['👨‍👧', 'family_man_girl', ''],
  ['👨‍👧‍👦', 'family_man_girl_boy', ''],
  ['👨‍👧‍👧', 'family_man_girl_girl', ''],
  ['👨‍👨‍👦', 'family_man_man_boy', ''],
  ['👨‍👨‍👦‍👦', 'family_man_man_boy_boy', ''],
  ['👨‍👨‍👧', 'family_man_man_girl', ''],
  ['👨‍👨‍👧‍👦', 'family_man_man_girl_boy', ''],
  ['👨‍👨‍👧‍👧', 'family_man_man_girl_girl', ''],
  ['👨‍👩‍👦', 'family_man_woman_boy', ''],
  ['👨‍👩‍👦‍👦', 'family_man_woman_boy_boy', ''],
  ['👨‍👩‍👧', 'family_man_woman_girl', ''],
  ['👨‍👩‍👧‍👦', 'family_man_woman_girl_boy', ''],
  ['👨‍👩‍👧‍👧', 'family_man_woman_girl_girl', ''],
  ['👩‍👦', 'family_woman_boy', ''],
  ['👩‍👦‍👦', 'family_woman_boy_boy', ''],
  ['👩‍👧', 'family_woman_girl', ''],
  ['👩‍👧‍👦', 'family_woman_girl_boy', ''],
  ['👩‍👧‍👧', 'family_woman_girl_girl', ''],
  ['👩‍👩‍👦', 'family_woman_woman_boy', ''],
  ['👩‍👩‍👦‍👦', 'family_woman_woman_boy_boy', ''],
  ['👩‍👩‍👧', 'family_woman_woman_girl', ''],
  ['👩‍👩‍👧‍👦', 'family_woman_woman_girl_boy', ''],
  ['👩‍👩‍👧‍👧', 'family_woman_woman_girl_girl', ''],
  ['🧑‍🌾', 'farmer', 'rancher gardener'],
  ['⏬', 'fast_down_button', 'arrow double'],
  ['⏩', 'fast_forward_button', 'arrow double'],
  ['⏪', 'fast_reverse_button', 'arrow double rewind'],
  ['⏫', 'fast_up_button', 'arrow double'],
  ['📠', 'fax_machine', ''],
  ['😨', 'fearful_face', 'scared'],
  ['♀️', 'female_sign', 'woman'],
  ['🎡', 'ferris_wheel', 'theme park amusement park'],
  ['⛴️', 'ferry', 'boat passenger'],
  ['🦟', 'fever', 'pest virus disease malaria mosquito'],
  ['🏑', 'field_hockey', 'ball game stick'],
  ['🪈', 'fife', 'pipe flute music recorder woodwind'],
  ['🗄️', 'file_cabinet', 'filing'],
  ['📁', 'file_folder', ''],
  ['🎦', 'film', 'movie cinema camera'],
  ['🎞️', 'film_frames', 'movie cinema'],
  ['📽️', 'film_projector', 'movie video cinema'],
  ['🔥', 'fire', 'tool flame'],
  ['🚒', 'fire_engine', 'truck'],
  ['🧯', 'fire_extinguisher', 'quench'],
  ['🧑‍🚒', 'firefighter', 'firetruck'],
  ['🎆', 'fireworks', 'celebration'],
  ['🌓', 'first_quarter_moon', ''],
  ['🌛', 'first_quarter_moon_face', ''],
  ['🍥', 'fish_cake_with_swirl', 'pastry'],
  ['🎣', 'fishing_pole', ''],
  ['🕔', 'five_o_clock', '5 00 5:00'],
  ['🕠', 'five_thirty', '5 5:30 clock'],
  ['🇦🇫', 'flag_afghanistan', ''],
  ['🇦🇱', 'flag_albania', ''],
  ['🇩🇿', 'flag_algeria', 'dz'],
  ['🇦🇸', 'flag_american_samoa', 'as'],
  ['🇦🇩', 'flag_andorra', 'ad'],
  ['🇦🇴', 'flag_angola', 'ao'],
  ['🇦🇮', 'flag_anguilla', 'ai'],
  ['🇦🇶', 'flag_antarctica', 'aq'],
  ['🇦🇬', 'flag_antigua_barbuda', ''],
  ['🇦🇷', 'flag_argentina', ''],
  ['🇦🇲', 'flag_armenia', 'am'],
  ['🇦🇼', 'flag_aruba', 'aw'],
  ['🇦🇨', 'flag_ascension_island', 'ac'],
  ['🇦🇺', 'flag_australia', ''],
  ['🇦🇹', 'flag_austria', 'at'],
  ['🇦🇿', 'flag_azerbaijan', ''],
  ['🇧🇸', 'flag_bahamas', 'bs'],
  ['🇧🇭', 'flag_bahrain', 'bh'],
  ['🇧🇩', 'flag_bangladesh', 'bd'],
  ['🇧🇧', 'flag_barbados', 'bb'],
  ['🇧🇾', 'flag_belarus', 'by'],
  ['🇧🇪', 'flag_belgium', ''],
  ['🇧🇿', 'flag_belize', 'bz'],
  ['🇧🇯', 'flag_benin', 'bj'],
  ['🇧🇲', 'flag_bermuda', 'bm'],
  ['🇧🇹', 'flag_bhutan', 'bt'],
  ['🇧🇴', 'flag_bolivia', ''],
  ['🇧🇦', 'flag_bosnia_herzegovina', 'ba'],
  ['🇧🇼', 'flag_botswana', 'bw'],
  ['🇧🇻', 'flag_bouvet_island', 'bv'],
  ['🇧🇷', 'flag_brazil', ''],
  ['🇮🇴', 'flag_british_indian_ocean_territory', 'io'],
  ['🇻🇬', 'flag_british_virgin_islands', 'vg'],
  ['🇧🇳', 'flag_brunei', 'bn'],
  ['🇧🇬', 'flag_bulgaria', 'bg'],
  ['🇧🇫', 'flag_burkina_faso', 'bf'],
  ['🇧🇮', 'flag_burundi', 'bi'],
  ['🇨🇮', 'flag_c_te_d_ivoire', 'ci'],
  ['🇰🇭', 'flag_cambodia', 'kh'],
  ['🇨🇲', 'flag_cameroon', 'cm'],
  ['🇨🇦', 'flag_canada', ''],
  ['🇮🇨', 'flag_canary_islands', 'ic'],
  ['🇨🇻', 'flag_cape_verde', 'cv'],
  ['🇧🇶', 'flag_caribbean_netherlands', 'bq'],
  ['🇰🇾', 'flag_cayman_islands', 'ky'],
  ['🇨🇫', 'flag_central_african_republic', 'cf'],
  ['🇪🇦', 'flag_ceuta_melilla', 'ea'],
  ['🇹🇩', 'flag_chad', 'td'],
  ['🇨🇱', 'flag_chile', 'cl'],
  ['🇨🇳', 'flag_china', 'cn'],
  ['🇨🇽', 'flag_christmas_island', 'cx'],
  ['🇨🇵', 'flag_clipperton_island', 'cp'],
  ['🇨🇨', 'flag_cocos_keeling_islands', 'cc'],
  ['🇨🇴', 'flag_colombia', ''],
  ['🇰🇲', 'flag_comoros', 'km'],
  ['🇨🇬', 'flag_congo_brazzaville', 'cg'],
  ['🇨🇩', 'flag_congo_kinshasa', 'cd'],
  ['🇨🇰', 'flag_cook_islands', 'ck'],
  ['🇨🇷', 'flag_costa_rica', 'cr'],
  ['🇭🇷', 'flag_croatia', 'hr'],
  ['🇨🇺', 'flag_cuba', ''],
  ['🇨🇼', 'flag_cura_ao', 'cw'],
  ['🇨🇾', 'flag_cyprus', ''],
  ['🇨🇿', 'flag_czechia', ''],
  ['🇩🇰', 'flag_denmark', 'dk'],
  ['🇩🇬', 'flag_diego_garcia', 'dg'],
  ['🇩🇯', 'flag_djibouti', ''],
  ['🇩🇲', 'flag_dominica', 'dm'],
  ['🇩🇴', 'flag_dominican_republic', ''],
  ['🇪🇨', 'flag_ecuador', ''],
  ['🇪🇬', 'flag_egypt', ''],
  ['🇸🇻', 'flag_el_salvador', 'sv'],
  ['🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'flag_england', 'gbeng'],
  ['🇬🇶', 'flag_equatorial_guinea', 'gq'],
  ['🇪🇷', 'flag_eritrea', ''],
  ['🇪🇪', 'flag_estonia', 'ee'],
  ['🇸🇿', 'flag_eswatini', 'sz'],
  ['🇪🇹', 'flag_ethiopia', ''],
  ['🇪🇺', 'flag_european_union', ''],
  ['🇫🇰', 'flag_falkland_islands', 'fk'],
  ['🇫🇴', 'flag_faroe_islands', 'fo'],
  ['🇫🇯', 'flag_fiji', 'fj'],
  ['🇫🇮', 'flag_finland', ''],
  ['🇫🇷', 'flag_france', ''],
  ['🇬🇫', 'flag_french_guiana', 'gf'],
  ['🇵🇫', 'flag_french_polynesia', 'pf'],
  ['🇹🇫', 'flag_french_southern_territories', 'tf'],
  ['🇬🇦', 'flag_gabon', ''],
  ['🇬🇲', 'flag_gambia', 'gm'],
  ['🇬🇪', 'flag_georgia', ''],
  ['🇩🇪', 'flag_germany', 'de'],
  ['🇬🇭', 'flag_ghana', ''],
  ['🇬🇮', 'flag_gibraltar', ''],
  ['🇬🇷', 'flag_greece', ''],
  ['🇬🇱', 'flag_greenland', 'gl'],
  ['🇬🇩', 'flag_grenada', 'gd'],
  ['🇬🇵', 'flag_guadeloupe', 'gp'],
  ['🇬🇺', 'flag_guam', ''],
  ['🇬🇹', 'flag_guatemala', 'gt'],
  ['🇬🇬', 'flag_guernsey', 'gg'],
  ['🇬🇳', 'flag_guinea', 'gn'],
  ['🇬🇼', 'flag_guinea_bissau', 'gw'],
  ['🇬🇾', 'flag_guyana', 'gy'],
  ['🇭🇹', 'flag_haiti', 'ht'],
  ['🇭🇲', 'flag_heard_mcdonald_islands', 'hm'],
  ['🇭🇳', 'flag_honduras', 'hn'],
  ['🇭🇰', 'flag_hong_kong_sar_china', 'hk'],
  ['🇭🇺', 'flag_hungary', ''],
  ['🇮🇸', 'flag_iceland', 'is'],
  ['⛳', 'flag_in_hole', 'golf'],
  ['🇮🇳', 'flag_india', ''],
  ['🇮🇩', 'flag_indonesia', 'id'],
  ['🇮🇷', 'flag_iran', ''],
  ['🇮🇶', 'flag_iraq', 'iq'],
  ['🇮🇪', 'flag_ireland', 'ie'],
  ['🇮🇲', 'flag_isle_of_man', 'im'],
  ['🇮🇱', 'flag_israel', 'il'],
  ['🇮🇹', 'flag_italy', ''],
  ['🇯🇲', 'flag_jamaica', 'jm'],
  ['🇯🇵', 'flag_japan', 'jp'],
  ['🇯🇪', 'flag_jersey', ''],
  ['🇯🇴', 'flag_jordan', ''],
  ['🇰🇿', 'flag_kazakhstan', 'kz'],
  ['🇰🇪', 'flag_kenya', ''],
  ['🇰🇮', 'flag_kiribati', ''],
  ['🇽🇰', 'flag_kosovo', 'xk'],
  ['🇰🇼', 'flag_kuwait', 'kw'],
  ['🇰🇬', 'flag_kyrgyzstan', 'kg'],
  ['🇦🇽', 'flag_land_islands', 'ax'],
  ['🇱🇦', 'flag_laos', ''],
  ['🇱🇻', 'flag_latvia', 'lv'],
  ['🇱🇧', 'flag_lebanon', 'lb'],
  ['🇱🇸', 'flag_lesotho', 'ls'],
  ['🇱🇷', 'flag_liberia', 'lr'],
  ['🇱🇾', 'flag_libya', 'ly'],
  ['🇱🇮', 'flag_liechtenstein', ''],
  ['🇱🇹', 'flag_lithuania', 'lt'],
  ['🇱🇺', 'flag_luxembourg', ''],
  ['🇲🇴', 'flag_macao_sar_china', 'mo'],
  ['🇲🇬', 'flag_madagascar', 'mg'],
  ['🇲🇼', 'flag_malawi', 'mw'],
  ['🇲🇾', 'flag_malaysia', 'my'],
  ['🇲🇻', 'flag_maldives', 'mv'],
  ['🇲🇱', 'flag_mali', 'ml'],
  ['🇲🇹', 'flag_malta', 'mt'],
  ['🇲🇭', 'flag_marshall_islands', 'mh'],
  ['🇲🇶', 'flag_martinique', 'mq'],
  ['🇲🇷', 'flag_mauritania', 'mr'],
  ['🇲🇺', 'flag_mauritius', 'mu'],
  ['🇾🇹', 'flag_mayotte', 'yt'],
  ['🇲🇽', 'flag_mexico', 'mx'],
  ['🇫🇲', 'flag_micronesia', 'fm'],
  ['🇲🇩', 'flag_moldova', 'md'],
  ['🇲🇨', 'flag_monaco', 'mc'],
  ['🇲🇳', 'flag_mongolia', 'mn'],
  ['🇲🇪', 'flag_montenegro', 'me'],
  ['🇲🇸', 'flag_montserrat', 'ms'],
  ['🇲🇦', 'flag_morocco', 'ma'],
  ['🇲🇿', 'flag_mozambique', 'mz'],
  ['🇲🇲', 'flag_myanmar_burma', 'mm flag: myanmar (burma)'],
  ['🇳🇦', 'flag_namibia', ''],
  ['🇳🇷', 'flag_nauru', 'nr'],
  ['🇳🇵', 'flag_nepal', 'np'],
  ['🇳🇱', 'flag_netherlands', 'nl'],
  ['🇳🇨', 'flag_new_caledonia', 'nc'],
  ['🇳🇿', 'flag_new_zealand', 'nz'],
  ['🇳🇮', 'flag_nicaragua', ''],
  ['🇳🇪', 'flag_niger', 'ne'],
  ['🇳🇬', 'flag_nigeria', 'ng'],
  ['🇳🇺', 'flag_niue', 'nu'],
  ['🇳🇫', 'flag_norfolk_island', 'nf'],
  ['🇰🇵', 'flag_north_korea', 'kp'],
  ['🇲🇰', 'flag_north_macedonia', 'mk'],
  ['🇲🇵', 'flag_northern_mariana_islands', 'mp'],
  ['🇳🇴', 'flag_norway', ''],
  ['🇴🇲', 'flag_oman', ''],
  ['🇵🇰', 'flag_pakistan', 'pk'],
  ['🇵🇼', 'flag_palau', 'pw'],
  ['🇵🇸', 'flag_palestinian_territories', 'ps'],
  ['🇵🇦', 'flag_panama', ''],
  ['🇵🇬', 'flag_papua_new_guinea', 'pg'],
  ['🇵🇾', 'flag_paraguay', 'py'],
  ['🇵🇪', 'flag_peru', ''],
  ['🇵🇭', 'flag_philippines', ''],
  ['🇵🇳', 'flag_pitcairn_islands', 'pn'],
  ['🇵🇱', 'flag_poland', 'pl'],
  ['🇵🇹', 'flag_portugal', 'pt'],
  ['🇵🇷', 'flag_puerto_rico', 'pr'],
  ['🇶🇦', 'flag_qatar', ''],
  ['🇷🇪', 'flag_r_union', 're'],
  ['🇷🇴', 'flag_romania', ''],
  ['🇷🇺', 'flag_russia', ''],
  ['🇷🇼', 'flag_rwanda', ''],
  ['🇸🇹', 'flag_s_o_tom_pr_ncipe', 'st'],
  ['🇼🇸', 'flag_samoa', 'ws'],
  ['🇸🇲', 'flag_san_marino', 'sm'],
  ['🇸🇦', 'flag_saudi_arabia', ''],
  ['🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'flag_scotland', 'gbsct'],
  ['🇸🇳', 'flag_senegal', 'sn'],
  ['🇷🇸', 'flag_serbia', 'rs'],
  ['🇸🇨', 'flag_seychelles', 'sc'],
  ['🇸🇱', 'flag_sierra_leone', 'sl'],
  ['🇸🇬', 'flag_singapore', 'sg'],
  ['🇸🇽', 'flag_sint_maarten', 'sx'],
  ['🇸🇰', 'flag_slovakia', 'sk'],
  ['🇸🇮', 'flag_slovenia', 'si'],
  ['🇸🇧', 'flag_solomon_islands', 'sb'],
  ['🇸🇴', 'flag_somalia', ''],
  ['🇿🇦', 'flag_south_africa', 'za'],
  ['🇬🇸', 'flag_south_georgia_south_sandwich_islands', 'gs'],
  ['🇰🇷', 'flag_south_korea', 'kr'],
  ['🇸🇸', 'flag_south_sudan', 'ss'],
  ['🇪🇸', 'flag_spain', 'es'],
  ['🇱🇰', 'flag_sri_lanka', 'lk'],
  ['🇧🇱', 'flag_st_barth_lemy', 'bl'],
  ['🇸🇭', 'flag_st_helena', 'sh'],
  ['🇰🇳', 'flag_st_kitts_nevis', 'kn'],
  ['🇱🇨', 'flag_st_lucia', 'lc'],
  ['🇲🇫', 'flag_st_martin', 'mf'],
  ['🇵🇲', 'flag_st_pierre_miquelon', 'pm'],
  ['🇻🇨', 'flag_st_vincent_grenadines', 'vc'],
  ['🇸🇩', 'flag_sudan', 'sd'],
  ['🇸🇷', 'flag_suriname', 'sr'],
  ['🇸🇯', 'flag_svalbard_jan_mayen', 'sj'],
  ['🇸🇪', 'flag_sweden', 'se'],
  ['🇨🇭', 'flag_switzerland', 'ch'],
  ['🇸🇾', 'flag_syria', ''],
  ['🇹🇷', 'flag_t_rkiye', 'tr'],
  ['🇹🇼', 'flag_taiwan', 'tw'],
  ['🇹🇯', 'flag_tajikistan', 'tj'],
  ['🇹🇿', 'flag_tanzania', 'tz'],
  ['🇹🇭', 'flag_thailand', ''],
  ['🇹🇱', 'flag_timor_leste', 'tl'],
  ['🇹🇬', 'flag_togo', 'tg'],
  ['🇹🇰', 'flag_tokelau', 'tk'],
  ['🇹🇴', 'flag_tonga', ''],
  ['🇹🇹', 'flag_trinidad_tobago', 'tt'],
  ['🇹🇦', 'flag_tristan_da_cunha', ''],
  ['🇹🇳', 'flag_tunisia', 'tn'],
  ['🇹🇲', 'flag_turkmenistan', 'tm'],
  ['🇹🇨', 'flag_turks_caicos_islands', 'tc'],
  ['🇹🇻', 'flag_tuvalu', 'tv'],
  ['🇺🇲', 'flag_u_s_outlying_islands', 'um'],
  ['🇻🇮', 'flag_u_s_virgin_islands', ''],
  ['🇺🇬', 'flag_uganda', ''],
  ['🇺🇦', 'flag_ukraine', 'ua'],
  ['🇦🇪', 'flag_united_arab_emirates', 'ae'],
  ['🇬🇧', 'flag_united_kingdom', 'gb'],
  ['🇺🇳', 'flag_united_nations', ''],
  ['🇺🇸', 'flag_united_states', 'us'],
  ['🇺🇾', 'flag_uruguay', 'uy'],
  ['🇺🇿', 'flag_uzbekistan', ''],
  ['🇻🇺', 'flag_vanuatu', 'vu'],
  ['🇻🇦', 'flag_vatican_city', ''],
  ['🇻🇪', 'flag_venezuela', ''],
  ['🇻🇳', 'flag_vietnam', 'vn'],
  ['🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'flag_wales', 'gbwls'],
  ['🇼🇫', 'flag_wallis_futuna', 'wf'],
  ['🇪🇭', 'flag_western_sahara', 'eh'],
  ['🇾🇪', 'flag_yemen', ''],
  ['🇿🇲', 'flag_zambia', 'zm'],
  ['🇿🇼', 'flag_zimbabwe', 'zw'],
  ['🦩', 'flamingo', 'tropical flamboyant'],
  ['⚜️', 'fleur_de_lis', ''],
  ['💪', 'flexed_biceps', 'comic muscle'],
  ['🪶', 'flight', 'bird feather plumage'],
  ['💾', 'floppy_disk', 'computer'],
  ['🎴', 'flower_playing_cards', 'game japanese'],
  ['😳', 'flushed_face', 'dazed'],
  ['🥏', 'flying_disc', 'ultimate'],
  ['🛸', 'flying_saucer', 'ufo'],
  ['🌫️', 'fog', 'cloud'],
  ['🌁', 'foggy', ''],
  ['🙏', 'folded_hands', 'ask pray high 5 please thanks high five'],
  ['🪭', 'folding_hand_fan', 'hot shy dance cooling flutter'],
  ['🦶', 'foot', 'kick stomp'],
  ['👣', 'footprint', 'clothing footprints'],
  ['🪠', 'force_cup', 'toilet plunger plumber suction'],
  ['♾️', 'forever', 'infinity unbounded universal'],
  ['🍴', 'fork_and_knife', 'cooking cutlery'],
  ['🍽️', 'fork_and_knife_with_plate', 'cooking'],
  ['🥠', 'fortune_cookie', 'prophecy'],
  ['⛲', 'fountain', ''],
  ['🖋️', 'fountain_pen', ''],
  ['🍀', 'four_leaf_clover', '4'],
  ['🕓', 'four_o_clock', '4 00 4:00'],
  ['🕟', 'four_thirty', '4 4:30 clock'],
  ['🪿', 'fowl', 'bird honk goose silly'],
  ['🦊', 'fox', 'face'],
  ['🖼️', 'framed_picture', 'art museum painting'],
  ['🆓', 'free_button', ''],
  ['🍟', 'french_fries', ''],
  ['🪟', 'fresh_air', 'view frame window opening transparent'],
  ['🍤', 'fried_shrimp', 'prawn tempura'],
  ['🐸', 'frog', 'face'],
  ['🐥', 'front_facing_baby_chick', 'bird'],
  ['☹️', 'frowning_face', ''],
  ['😦', 'frowning_face_with_open_mouth', ''],
  ['🍳', 'frying', 'egg pan cooking breakfast'],
  ['⛽', 'fuel_pump', 'gas diesel station fuelpump'],
  ['🌕', 'full_moon', ''],
  ['🌝', 'full_moon_face', 'bright'],
  ['⚱️', 'funeral_urn', 'ashes death'],
  ['🎲', 'game_die', 'dice'],
  ['🧄', 'garlic', 'flavoring'],
  ['💎', 'gem_stone', 'jewel diamond'],
  ['🧒', 'gender_neutral', 'child young unspecified gender'],
  ['🧞', 'genie', 'djinn'],
  ['🫚', 'ginger_root', 'beer spice'],
  ['🥛', 'glass_of_milk', 'drink'],
  ['🌎', 'globe_showing_americas', 'earth world'],
  ['🌏', 'globe_showing_asia_australia', 'earth world'],
  ['🌍', 'globe_showing_europe_africa', 'earth world'],
  ['🌐', 'globe_with_meridians', 'earth world'],
  ['🧤', 'gloves', 'hand'],
  ['🌟', 'glowing_star', 'shining sparkle glittery'],
  ['🥅', 'goal_net', ''],
  ['🐐', 'goat', 'zodiac capricorn'],
  ['🦍', 'gorilla', ''],
  ['🎓', 'graduation_cap', 'hat clothing celebration'],
  ['🍇', 'grape', 'fruit grapes'],
  ['🪦', 'grave', 'cemetery headstone graveyard tombstone'],
  ['🍏', 'green_apple', 'fruit'],
  ['📗', 'green_book', ''],
  ['🟢', 'green_circle', ''],
  ['💚', 'green_heart', ''],
  ['🥗', 'green_salad', 'food'],
  ['🟩', 'green_square', ''],
  ['🩶', 'grey_heart', 'gray slate silver'],
  ['😬', 'grimacing_face', 'grimace'],
  ['😺', 'grinning_cat', 'face open mouth smile'],
  ['😸', 'grinning_cat_with_smiling_eyes', 'face smile'],
  ['😀', 'grinning_face', ''],
  ['😃', 'grinning_face_with_big_eyes', 'open mouth smile'],
  ['😄', 'grinning_face_with_smiling_eyes', 'open mouth smile'],
  ['😅', 'grinning_face_with_sweat', 'cold open smile'],
  ['😆', 'grinning_squinting_face', 'laugh mouth smile satisfied'],
  ['💗', 'growing_heart', 'pulse excited nervous'],
  ['👲', 'gua_pi_mao', 'cap hat person skullcap person with skullcap'],
  ['💂', 'guard', ''],
  ['🦮', 'guide_dog', 'blind accessibility'],
  ['🎸', 'guitar', 'music instrument'],
  ['🥟', 'gy_za', 'jiaozi pierogi dumpling empanada potsticker'],
  ['🪮', 'hair_pick', 'afro comb'],
  ['🔨', 'hammer', 'tool'],
  ['⚒️', 'hammer_and_pick', 'tool'],
  ['🛠️', 'hammer_and_wrench', 'tool spanner'],
  ['🐹', 'hamster', 'pet face'],
  ['🤌', 'hand_gesture', 'fingers pinched sarcastic interrogation pinched fingers'],
  ['🖐️', 'hand_with_fingers_splayed', ''],
  ['🫰', 'hand_with_index_finger_and_thumb_crossed', 'love snap heart money expensive'],
  ['👜', 'handbag', 'purse clothing'],
  ['🤝', 'handshake', 'meeting agreement'],
  ['🪂', 'hang_glide', 'skydive parasail parachute'],
  ['🥢', 'hashi', 'chopsticks'],
  ['🐣', 'hatching_chick', 'baby bird'],
  ['🙂‍↔️', 'head_shaking_horizontally', 'no shake'],
  ['🙂‍↕️', 'head_shaking_vertically', 'nod yes'],
  ['🧑‍⚕️', 'health_worker', 'nurse doctor therapist healthcare'],
  ['🙉', 'hear_no_evil_monkey', 'face forbidden'],
  ['💟', 'heart_decoration', ''],
  ['❣️', 'heart_exclamation', 'mark punctuation'],
  ['🫶', 'heart_hands', 'love'],
  ['❤️‍🔥', 'heart_on_fire', 'burn love lust sacred heart'],
  ['♥️', 'heart_suit', 'card game'],
  ['💘', 'heart_with_arrow', 'cupid'],
  ['💝', 'heart_with_ribbon', 'valentine'],
  ['🪨', 'heavy', 'rock solid stone boulder'],
  ['💲', 'heavy_dollar_sign', 'money currency'],
  ['🟰', 'heavy_equals_sign', 'math equality'],
  ['🚁', 'helicopter', 'vehicle'],
  ['🌿', 'herb', 'leaf'],
  ['🦬', 'herd', 'bison wisent buffalo'],
  ['🌺', 'hibiscus', 'flower'],
  ['👠', 'high_heeled_shoe', 'woman clothing'],
  ['🚄', 'high_speed_train', 'railway shinkansen'],
  ['⚡', 'high_voltage', 'zap danger electric lightning'],
  ['🥾', 'hiking_boot', 'camping backpacking'],
  ['🛕', 'hindu_temple', ''],
  ['🦛', 'hippo', 'hippopotamus'],
  ['🕳️', 'hole', ''],
  ['⭕', 'hollow_red_circle', 'large'],
  ['🏠', 'home', 'house'],
  ['🦡', 'honey_badger', 'pester'],
  ['🍯', 'honey_pot', 'sweet honeypot'],
  ['🏀', 'hoop', 'ball basketball'],
  ['🚥', 'horizontal_traffic_light', 'signal'],
  ['🐴', 'horse_face', ''],
  ['🏇', 'horse_racing', 'jockey racehorse'],
  ['🏥', 'hospital', 'doctor medicine'],
  ['☕', 'hot_beverage', 'tea drink coffee steaming'],
  ['🌭', 'hot_dog', 'hotdog sausage frankfurter'],
  ['🥵', 'hot_face', 'feverish sweating red faced heat stroke'],
  ['🌶️', 'hot_pepper', ''],
  ['♨️', 'hot_springs', 'steaming hotsprings'],
  ['⌛', 'hourglass_done', 'sand timer'],
  ['⏳', 'hourglass_not_done', 'sand timer'],
  ['🏡', 'house_with_garden', 'home'],
  ['🏘️', 'houses', ''],
  ['💯', 'hundred_points', '100 full score'],
  ['😯', 'hushed_face', 'stunned surprised'],
  ['🛖', 'hut', 'yurt house roundhouse'],
  ['ℹ️', 'i', 'information'],
  ['🍨', 'ice_cream', 'sweet dessert'],
  ['🧊', 'ice_cube', 'cold iceberg'],
  ['🏒', 'ice_hockey', 'game puck stick'],
  ['⛸️', 'ice_skate', ''],
  ['🆔', 'id_button', 'identity'],
  ['🪪', 'identification_card', 'license security credentials'],
  ['📥', 'inbox_tray', 'mail letter receive'],
  ['📨', 'incoming_envelope', 'email e mail letter receive'],
  ['🫵', 'index_pointing_at_the_viewer', 'you'],
  ['☝️', 'index_pointing_up', 'hand finger'],
  ['🔤', 'input_latin_letters', 'abc alphabet'],
  ['🔡', 'input_latin_lowercase', 'abcd letters'],
  ['🔠', 'input_latin_uppercase', 'abcd letters'],
  ['🔢', 'input_numbers', '1234'],
  ['🔣', 'input_symbols', ''],
  ['🧇', 'iron', 'waffle breakfast indecisive'],
  ['🎃', 'jack_o_lantern', 'halloween celebration'],
  ['🉑', 'japanese_acceptable_button', 'ideograph'],
  ['🈸', 'japanese_application_button', 'ideograph'],
  ['🉐', 'japanese_bargain_button', 'ideograph'],
  ['🏯', 'japanese_castle', ''],
  ['㊗️', 'japanese_congratulations_button', 'ideograph'],
  ['🈹', 'japanese_discount_button', 'ideograph'],
  ['🎎', 'japanese_dolls', 'festival celebration'],
  ['🈚', 'japanese_free_of_charge_button', 'ideograph'],
  ['🈁', 'japanese_here_button', 'katakana'],
  ['🈷️', 'japanese_monthly_amount_button', 'ideograph'],
  ['🈵', 'japanese_no_vacancy_button', 'ideograph'],
  ['🈶', 'japanese_not_free_of_charge_button', 'ideograph'],
  ['🈺', 'japanese_open_for_business_button', 'ideograph'],
  ['🈴', 'japanese_passing_grade_button', 'ideograph'],
  ['🏣', 'japanese_post_office', ''],
  ['🈲', 'japanese_prohibited_button', 'ideograph'],
  ['🈯', 'japanese_reserved_button', 'ideograph'],
  ['㊙️', 'japanese_secret_button', 'ideograph'],
  ['🈂️', 'japanese_service_charge_button', 'katakana'],
  ['🔰', 'japanese_symbol_for_beginner', 'leaf chevron'],
  ['🈳', 'japanese_vacancy_button', 'ideograph'],
  ['🫙', 'jar', 'empty sauce store condiment container'],
  ['👖', 'jeans', 'pants clothing trousers'],
  ['🦘', 'joey', 'jump kangaroo marsupial'],
  ['🃏', 'joker', 'card game wildcard'],
  ['🏺', 'jug', 'drink zodiac amphora cooking aquarius'],
  ['🕋', 'kaaba', 'islam muslim religion'],
  ['🎤', 'karaoke', 'mic microphone'],
  ['⌨️', 'keyboard', 'computer'],
  ['#️⃣', 'keycap', ''],
  ['0️⃣', 'keycap_0', ''],
  ['1️⃣', 'keycap_1', ''],
  ['🔟', 'keycap_10', ''],
  ['2️⃣', 'keycap_2', ''],
  ['3️⃣', 'keycap_3', ''],
  ['4️⃣', 'keycap_4', ''],
  ['5️⃣', 'keycap_5', ''],
  ['6️⃣', 'keycap_6', ''],
  ['7️⃣', 'keycap_7', ''],
  ['8️⃣', 'keycap_8', ''],
  ['9️⃣', 'keycap_9', ''],
  ['🛴', 'kick_scooter', ''],
  ['🫘', 'kidney', 'food beans legume'],
  ['👘', 'kimono', 'clothing'],
  ['👑', 'king', 'crown queen clothing'],
  ['💏', 'kiss', 'couple'],
  ['👨‍❤️‍💋‍👨', 'kiss_man_man', 'couple'],
  ['💋', 'kiss_mark', 'lips'],
  ['👩‍❤️‍💋‍👨', 'kiss_woman_man', 'couple'],
  ['👩‍❤️‍💋‍👩', 'kiss_woman_woman', 'couple'],
  ['😽', 'kissing_cat', 'eye face'],
  ['😗', 'kissing_face', ''],
  ['😚', 'kissing_face_with_closed_eyes', ''],
  ['😙', 'kissing_face_with_smiling_eyes', 'smile'],
  ['🔪', 'kitchen_knife', 'tool hocho weapon cooking'],
  ['🪁', 'kite', 'fly soar'],
  ['🥝', 'kiwi_fruit', 'food'],
  ['🪢', 'knot', 'tie rope twine twist tangled'],
  ['🐨', 'koala', 'face marsupial'],
  ['🥼', 'lab_coat', 'doctor scientist experiment'],
  ['🏷️', 'label', ''],
  ['🥍', 'lacrosse', 'ball goal stick'],
  ['🐞', 'lady_beetle', 'insect ladybug ladybird'],
  ['🧧', 'lai_see', 'gift money hóngbāo good luck red envelope'],
  ['💻', 'laptop', 'pc computer personal'],
  ['🔷', 'large_blue_diamond', 'geometric'],
  ['🔶', 'large_orange_diamond', 'geometric'],
  ['🌗', 'last_quarter_moon', ''],
  ['🌜', 'last_quarter_moon_face', ''],
  ['⏮️', 'last_track_button', 'arrow triangle previous scene previous track'],
  ['🧼', 'lather', 'bar soap bathing cleaning soapdish'],
  ['✝️', 'latin_cross', 'religion christian'],
  ['🧑‍⚖️', 'law', 'judge scales justice'],
  ['🦥', 'lazy', 'slow sloth'],
  ['🍃', 'leaf_fluttering_in_wind', 'blow'],
  ['📒', 'ledger', 'notebook'],
  ['⬅️', 'left_arrow', 'west cardinal direction'],
  ['↪️', 'left_arrow_curving_right', ''],
  ['🤛', 'left_facing_fist', 'leftwards'],
  ['🛅', 'left_luggage', 'locker baggage'],
  ['↔️', 'left_right_arrow', ''],
  ['🗨️', 'left_speech_bubble', 'dialog balloon'],
  ['🫲', 'leftwards_hand', ''],
  ['🫷', 'leftwards_pushing_hand', 'stop wait refuse high five'],
  ['🍋', 'lemon', 'fruit citrus'],
  ['🦁', 'leo', 'lion face zodiac'],
  ['🐆', 'leopard', ''],
  ['🎚️', 'level_slider', 'music'],
  ['♎', 'libra', 'scales zodiac balance justice'],
  ['🛗', 'lift', 'hoist elevator accessibility'],
  ['🩵', 'light_blue_heart', 'cyan teal'],
  ['💡', 'light_bulb', 'idea comic electric'],
  ['🚈', 'light_rail', 'railway'],
  ['🦵', 'limb', 'leg kick'],
  ['🍋‍🟩', 'lime', 'fruit citrus tropical'],
  ['🔗', 'link', ''],
  ['🖇️', 'linked_paperclips', ''],
  ['👄', 'lips', 'mouth'],
  ['🚮', 'litter_in_bin_sign', 'litter bin'],
  ['🦎', 'lizard', 'reptile'],
  ['🍞', 'loaf', 'bread'],
  ['🔒', 'locked', 'closed'],
  ['🔐', 'locked_with_key', 'closed secure'],
  ['🔏', 'locked_with_pen', 'ink nib privacy'],
  ['🪵', 'log', 'wood lumber timber'],
  ['🍭', 'lollipop', 'candy sweet dessert'],
  ['🪘', 'long_drum', 'beat conga rhythm'],
  ['🧴', 'lotion_bottle', 'shampoo sunscreen moisturizer'],
  ['🪷', 'lotus', 'flower purity buddhism hinduism'],
  ['😭', 'loudly_crying_face', 'sad sob tear'],
  ['🏩', 'love_hotel', ''],
  ['💌', 'love_letter', 'mail heart'],
  ['🤟', 'love_you_gesture', 'ily hand'],
  ['🪫', 'low_energy', 'electronic low battery'],
  ['🫁', 'lungs', 'organ breath exhalation inhalation respiration'],
  ['🪻', 'lupine', 'flower hyacinth lavender bluebonnet snapdragon'],
  ['🤥', 'lying_face', 'lie pinocchio'],
  ['🧙', 'mage', 'witch wizard sorcerer sorceress'],
  ['🪰', 'maggot', 'fly pest disease rotting'],
  ['🪄', 'magic_wand', 'witch wizard'],
  ['🧲', 'magnet', 'magnetic horseshoe attraction'],
  ['🔍', 'magnifying_glass_tilted_left', 'tool search'],
  ['🔎', 'magnifying_glass_tilted_right', 'tool search'],
  ['🀄', 'mahjong_red_dragon', 'game'],
  ['💄', 'makeup', 'lipstick cosmetics'],
  ['🐏', 'male', 'ram aries sheep zodiac'],
  ['♂️', 'male_sign', 'man'],
  ['👨‍🎨', 'man_artist', 'palette'],
  ['👨‍🚀', 'man_astronaut', 'rocket'],
  ['👨‍🦲', 'man_bald', 'adult'],
  ['🧔‍♂️', 'man_beard', ''],
  ['🚴‍♂️', 'man_biking', 'bicycle cyclist'],
  ['👱‍♂️', 'man_blond_hair', 'blond haired man'],
  ['⛹️‍♂️', 'man_bouncing_ball', ''],
  ['🙇‍♂️', 'man_bowing', 'favor sorry apology gesture'],
  ['🤸‍♂️', 'man_cartwheeling', 'gymnastics'],
  ['🧗‍♂️', 'man_climbing', 'climber'],
  ['👷‍♂️', 'man_construction_worker', ''],
  ['👨‍🍳', 'man_cook', 'chef'],
  ['👨‍🦱', 'man_curly_hair', 'adult'],
  ['🕺', 'man_dancing', 'dance'],
  ['🕵️‍♂️', 'man_detective', 'spy sleuth'],
  ['🧝‍♂️', 'man_elf', 'magical'],
  ['🤦‍♂️', 'man_facepalming', 'disbelief exasperation'],
  ['👨‍🏭', 'man_factory_worker', 'assembly industrial'],
  ['🧚‍♂️', 'man_fairy', 'puck oberon'],
  ['👨‍🌾', 'man_farmer', 'rancher gardener'],
  ['👨‍🍼', 'man_feeding_baby', 'nursing'],
  ['👨‍🚒', 'man_firefighter', 'firetruck'],
  ['🙍‍♂️', 'man_frowning', 'gesture'],
  ['🧞‍♂️', 'man_genie', 'djinn'],
  ['🙅‍♂️', 'man_gesturing_no', 'hand gesture forbidden prohibited'],
  ['🙆‍♂️', 'man_gesturing_ok', 'hand gesture'],
  ['💇‍♂️', 'man_getting_haircut', ''],
  ['💆‍♂️', 'man_getting_massage', 'face'],
  ['🏌️‍♂️', 'man_golfing', ''],
  ['💂‍♂️', 'man_guard', ''],
  ['👨‍⚕️', 'man_health_worker', 'nurse doctor therapist healthcare'],
  ['🧘‍♂️', 'man_in_lotus_position', 'yoga meditation'],
  ['👨‍🦽', 'man_in_manual_wheelchair', 'accessibility'],
  ['👨‍🦽‍➡️', 'man_in_manual_wheelchair_facing_right', 'accessibility'],
  ['👨‍🦼', 'man_in_motorized_wheelchair', 'accessibility'],
  ['👨‍🦼‍➡️', 'man_in_motorized_wheelchair_facing_right', 'accessibility'],
  ['🧖‍♂️', 'man_in_steamy_room', 'sauna steam room'],
  ['🤵‍♂️', 'man_in_tuxedo', ''],
  ['👨‍⚖️', 'man_judge', 'law scales justice'],
  ['🤹‍♂️', 'man_juggling', 'multitask'],
  ['🧎‍♂️', 'man_kneeling', ''],
  ['🧎‍♂️‍➡️', 'man_kneeling_facing_right', ''],
  ['🏋️‍♂️', 'man_lifting_weights', 'weight lifter'],
  ['🧙‍♂️', 'man_mage', 'wizard sorcerer'],
  ['👨‍🔧', 'man_mechanic', 'plumber electrician tradesperson'],
  ['🚵‍♂️', 'man_mountain_biking', 'bike bicycle cyclist'],
  ['👨‍💼', 'man_office_worker', 'manager business architect white collar'],
  ['👨‍✈️', 'man_pilot', 'plane'],
  ['🤾‍♂️', 'man_playing_handball', ''],
  ['🤽‍♂️', 'man_playing_water_polo', ''],
  ['👮‍♂️', 'man_police_officer', 'cop'],
  ['🙎‍♂️', 'man_pouting', 'gesture'],
  ['🙋‍♂️', 'man_raising_hand', 'gesture'],
  ['👨‍🦰', 'man_red_hair', 'adult'],
  ['🚣‍♂️', 'man_rowing_boat', 'rowboat'],
  ['🏃‍♂️', 'man_running', 'racing marathon'],
  ['🏃‍♂️‍➡️', 'man_running_facing_right', 'racing marathon'],
  ['👞', 'man_s_shoe', 'clothing'],
  ['👨‍🔬', 'man_scientist', 'chemist engineer biologist physicist'],
  ['🤷‍♂️', 'man_shrugging', 'doubt ignorance indifference'],
  ['👨‍🎤', 'man_singer', 'rock star actor entertainer'],
  ['🧍‍♂️', 'man_standing', ''],
  ['👨‍🎓', 'man_student', 'graduate'],
  ['🦸‍♂️', 'man_superhero', 'good superpower'],
  ['🦹‍♂️', 'man_supervillain', 'evil criminal superpower'],
  ['🏄‍♂️', 'man_surfing', ''],
  ['🏊‍♂️', 'man_swimming', ''],
  ['👨‍🏫', 'man_teacher', 'lecturer professor instructor'],
  ['👨‍💻', 'man_technologist', 'coder inventor software developer'],
  ['💁‍♂️', 'man_tipping_hand', 'sassy'],
  ['🧛‍♂️', 'man_vampire', 'undead dracula'],
  ['🚶‍♂️', 'man_walking', 'hike'],
  ['🚶‍♂️‍➡️', 'man_walking_facing_right', 'hike'],
  ['👳‍♂️', 'man_wearing_turban', ''],
  ['👨‍🦳', 'man_white_hair', 'adult'],
  ['👰‍♂️', 'man_with_veil', ''],
  ['👨‍🦯', 'man_with_white_cane', 'blind accessibility'],
  ['👨‍🦯‍➡️', 'man_with_white_cane_facing_right', 'blind accessibility'],
  ['🧟‍♂️', 'man_zombie', 'undead walking dead'],
  ['🥭', 'mango', 'fruit tropical'],
  ['🕰️', 'mantelpiece_clock', ''],
  ['🦽', 'manual_wheelchair', 'accessibility'],
  ['🗾', 'map_of_japan', ''],
  ['🍁', 'maple_leaf', 'falling'],
  ['🥋', 'martial_arts_uniform', 'judo karate taekwondo'],
  ['🪬', 'mary', 'hand hamsa amulet fatima miriam protection'],
  ['🧉', 'mate', 'drink'],
  ['🍖', 'meat_on_bone', ''],
  ['🦾', 'mechanical_arm', 'prosthetic accessibility'],
  ['🦿', 'mechanical_leg', 'prosthetic accessibility'],
  ['⚕️', 'medical_symbol', 'staff medicine aesculapius'],
  ['📣', 'megaphone', 'cheering'],
  ['🍈', 'melon', 'fruit'],
  ['🫠', 'melting_face', 'liquid dissolve disappear'],
  ['📝', 'memo', 'pencil'],
  ['👬', 'men_holding_hands', 'man twins couple gemini zodiac'],
  ['🚹', 'men_s_room', 'wc man toilet bathroom lavatory restroom'],
  ['👯‍♂️', 'men_with_bunny_ears', 'dancer partying'],
  ['🤼‍♂️', 'men_wrestling', 'wrestle'],
  ['❤️‍🩹', 'mending_heart', 'well healthier improving recovering recuperating'],
  ['🕎', 'menorah', 'religion candelabrum candlestick'],
  ['🧜‍♀️', 'mermaid', 'merwoman'],
  ['🧜', 'merperson', 'merman mermaid merwoman'],
  ['🪙', 'metal', 'coin gold money silver treasure'],
  ['🚇', 'metro', 'subway'],
  ['🔬', 'microscope', 'tool science'],
  ['🖕', 'middle_finger', 'hand'],
  ['🪖', 'military_helmet', 'army soldier warrior'],
  ['🎖️', 'military_medal', 'celebration'],
  ['🌌', 'milky_way', 'space'],
  ['🤯', 'mind_blown', 'shocked exploding head'],
  ['🚐', 'minibus', ''],
  ['⛏️', 'mining', 'pick tool'],
  ['🪞', 'mirror', 'speculum reflector reflection'],
  ['🪩', 'mirror_ball', 'dance disco party glitter'],
  ['🗿', 'moai', 'face moyai statue'],
  ['📱', 'mobile_phone', 'cell telephone'],
  ['📴', 'mobile_phone_off', 'cell telephone'],
  ['📲', 'mobile_phone_with_arrow', 'cell receive'],
  ['🩼', 'mobility_aid', 'cane hurt stick crutch disability'],
  ['💰', 'money_bag', 'dollar moneybag'],
  ['🤑', 'money_mouth_face', ''],
  ['💸', 'money_with_wings', 'fly bill banknote'],
  ['🐒', 'monkey', ''],
  ['🐵', 'monkey_face', ''],
  ['🚝', 'monorail', 'vehicle'],
  ['🥮', 'moon_cake', 'autumn yuèbǐng festival'],
  ['🎑', 'moon_viewing_ceremony', 'celebration'],
  ['🕌', 'mosque', 'islam muslim religion'],
  ['🛥️', 'motor_boat', 'motorboat'],
  ['🛵', 'motor_scooter', ''],
  ['🏍️', 'motorcycle', 'racing'],
  ['🦼', 'motorized_wheelchair', 'accessibility'],
  ['🗻', 'mount_fuji', 'mountain'],
  ['⛰️', 'mountain', ''],
  ['🚠', 'mountain_cableway', 'gondola'],
  ['🚞', 'mountain_railway', 'car'],
  ['🐁', 'mouse', ''],
  ['🐭', 'mouse_face', ''],
  ['🪤', 'mouse_trap', 'bait snare mousetrap'],
  ['🎥', 'movie_camera', 'cinema'],
  ['🤶', 'mrs_claus', 'mother christmas celebration'],
  ['🍄', 'mushroom', 'toadstool'],
  ['🎹', 'musical_keyboard', 'piano instrument'],
  ['🎵', 'musical_note', ''],
  ['🎶', 'musical_notes', ''],
  ['🎼', 'musical_score', ''],
  ['🔇', 'muted_speaker', 'quiet silent'],
  ['🧑‍🎄', 'mx_claus', 'christmas'],
  ['🫓', 'naan', 'pita arepa lavash flatbread'],
  ['💅', 'nail_polish', 'care manicure cosmetics'],
  ['📛', 'name_badge', ''],
  ['🏞️', 'national_park', ''],
  ['🤢', 'nauseated_face', 'vomit'],
  ['🧣', 'neck', 'scarf'],
  ['👔', 'necktie', 'clothing'],
  ['🤓', 'nerd_face', 'geek'],
  ['🪺', 'nest_with_eggs', 'nesting'],
  ['🪆', 'nesting_dolls', 'russia'],
  ['😐', 'neutral_face', 'meh deadpan'],
  ['🆕', 'new_button', ''],
  ['🌑', 'new_moon', 'dark'],
  ['🌚', 'new_moon_face', ''],
  ['📰', 'news', 'paper newspaper'],
  ['⏭️', 'next_track_button', 'arrow triangle next scene'],
  ['🆖', 'ng_button', ''],
  ['🌃', 'night_with_stars', ''],
  ['🕘', 'nine_o_clock', '9 00 9:00'],
  ['🕤', 'nine_thirty', '9 9:30 clock'],
  ['🥷', 'ninja', 'hidden fighter stealth'],
  ['🚳', 'no_bicycles', 'bike forbidden prohibited'],
  ['⛔', 'no_entry', 'not traffic forbidden prohibited'],
  ['🚯', 'no_littering', 'not forbidden prohibited'],
  ['📵', 'no_mobile_phones', 'cell forbidden'],
  ['🔞', 'no_one_under_eighteen', '18 underage prohibited age restriction'],
  ['🚷', 'no_pedestrians', 'not forbidden prohibited'],
  ['🚭', 'no_smoking', 'not forbidden prohibited'],
  ['🚱', 'non_potable_water', 'non drinking'],
  ['👃', 'nose', 'body'],
  ['📓', 'notebook', ''],
  ['📔', 'notebook_with_decorative_cover', 'decorated'],
  ['🔩', 'nut_and_bolt', 'tool'],
  ['🅾️', 'o_button_blood_type', 'o button (blood type)'],
  ['🐙', 'octopus', ''],
  ['🍢', 'oden', 'kebab stick skewer seafood'],
  ['🏢', 'office_building', ''],
  ['🧑‍💼', 'office_worker', 'manager business architect white collar'],
  ['🛢️', 'oil_drum', ''],
  ['🆗', 'ok_button', ''],
  ['👌', 'ok_hand', ''],
  ['🗝️', 'old_key', 'clue lock'],
  ['👴', 'old_man', 'adult'],
  ['👵', 'old_woman', 'adult'],
  ['🧓', 'older_person', 'adult gender neutral unspecified gender'],
  ['🫒', 'olive', 'food'],
  ['🕉️', 'om', 'hindu religion'],
  ['🔛', 'on_arrow', 'mark'],
  ['🚘', 'oncoming_automobile', 'car'],
  ['🚍', 'oncoming_bus', ''],
  ['👊', 'oncoming_fist', 'hand punch clenched'],
  ['🚔', 'oncoming_police_car', ''],
  ['🚖', 'oncoming_taxi', ''],
  ['🕐', 'one_o_clock', '1 00 1:00'],
  ['🩲', 'one_piece', 'briefs swimsuit underwear bathing suit'],
  ['🩱', 'one_piece_swimsuit', 'bathing suit'],
  ['🕜', 'one_thirty', '1 1:30 clock'],
  ['🧅', 'onion', 'flavoring'],
  ['📖', 'open_book', ''],
  ['📂', 'open_file_folder', ''],
  ['👐', 'open_hands', ''],
  ['📭', 'open_mailbox_with_lowered_flag', 'postbox'],
  ['📬', 'open_mailbox_with_raised_flag', 'postbox'],
  ['💿', 'optical_disk', 'cd computer'],
  ['📙', 'orange_book', ''],
  ['🟠', 'orange_circle', ''],
  ['🧡', 'orange_heart', ''],
  ['🟧', 'orange_square', ''],
  ['☦️', 'orthodox_cross', 'religion christian'],
  ['🦦', 'otter', 'fishing playful'],
  ['🪼', 'ouch', 'burn jelly marine stinger jellyfish invertebrate'],
  ['📤', 'outbox_tray', 'mail sent letter'],
  ['🦉', 'owl', 'bird wise'],
  ['🐂', 'ox', 'bull taurus zodiac'],
  ['🦪', 'oyster', 'pearl diving'],
  ['🅿️', 'p_button', 'parking'],
  ['📄', 'page_facing_up', 'document'],
  ['📃', 'page_with_curl', 'document'],
  ['📟', 'pager', ''],
  ['🖌️', 'paintbrush', 'painting'],
  ['🫳', 'palm_down_hand', 'drop shoo dismiss'],
  ['🌴', 'palm_tree', ''],
  ['🫴', 'palm_up_hand', 'come catch offer beckon'],
  ['🤲', 'palms_up_together', 'prayer'],
  ['🐼', 'panda', 'face'],
  ['📎', 'paperclip', ''],
  ['📦', 'parcel', 'box package'],
  ['〽️', 'part_alternation_mark', ''],
  ['🎉', 'party_popper', 'tada celebration'],
  ['🥳', 'partying_face', 'hat horn celebration'],
  ['🚢', 'passenger', 'ship boat'],
  ['🛳️', 'passenger_ship', ''],
  ['🛂', 'passport_control', ''],
  ['🔑', 'password', 'key lock'],
  ['🍝', 'pasta', 'spaghetti'],
  ['⏸️', 'pause_button', 'bar double vertical'],
  ['🐾', 'paw_prints', 'feet'],
  ['🫛', 'pea_pod', 'beans legume edamame vegetable'],
  ['☮️', 'peace_symbol', ''],
  ['🍑', 'peach', 'fruit'],
  ['🦚', 'peahen', 'bird proud peacock ostentatious'],
  ['🥜', 'peanut', 'food peanuts vegetable'],
  ['🍐', 'pear', 'fruit'],
  ['✏️', 'pencil', ''],
  ['🐧', 'penguin', 'bird'],
  ['😔', 'pensive_face', 'dejected'],
  ['🧑‍🤝‍🧑', 'people_holding_hands', 'couple person'],
  ['🫂', 'people_hugging', 'hello thanks goodbye'],
  ['👯', 'people_with_bunny_ears', 'dancer partying'],
  ['🤼', 'people_wrestling', 'wrestle wrestler'],
  ['🎭', 'performing_arts', 'mask theater theatre'],
  ['😣', 'persevering_face', 'persevere'],
  ['🧑‍🦲', 'person_bald', 'adult gender neutral unspecified gender'],
  ['🧔', 'person_beard', ''],
  ['🚴', 'person_biking', 'bicycle cyclist'],
  ['👱', 'person_blond_hair', 'blond haired person'],
  ['⛹️', 'person_bouncing_ball', ''],
  ['🙇', 'person_bowing', 'sorry apology gesture'],
  ['🤸', 'person_cartwheeling', 'gymnastics'],
  ['🧗', 'person_climbing', 'climber'],
  ['🧑‍🦱', 'person_curly_hair', 'adult gender neutral unspecified gender'],
  ['🤦', 'person_facepalming', 'disbelief exasperation'],
  ['🧑‍🍼', 'person_feeding_baby', 'nursing'],
  ['🤺', 'person_fencing', 'sword fencer'],
  ['🙍', 'person_frowning', 'gesture'],
  ['🙅', 'person_gesturing_no', 'hand gesture forbidden prohibited'],
  ['🙆', 'person_gesturing_ok', 'hand gesture'],
  ['💇', 'person_getting_haircut', 'barber beauty parlor'],
  ['💆', 'person_getting_massage', 'face salon'],
  ['🏌️', 'person_golfing', 'ball'],
  ['🛌', 'person_in_bed', 'hotel sleep good night'],
  ['🧘', 'person_in_lotus_position', 'yoga meditation'],
  ['🧑‍🦽', 'person_in_manual_wheelchair', 'accessibility'],
  ['🧑‍🦽‍➡️', 'person_in_manual_wheelchair_facing_right', 'accessibility'],
  ['🧑‍🦼', 'person_in_motorized_wheelchair', 'accessibility'],
  ['🧑‍🦼‍➡️', 'person_in_motorized_wheelchair_facing_right', 'accessibility'],
  ['🧖', 'person_in_steamy_room', 'sauna steam room'],
  ['🕴️', 'person_in_suit_levitating', 'business'],
  ['🤵', 'person_in_tuxedo', 'groom'],
  ['🤹', 'person_juggling', 'skill juggle balance multitask'],
  ['🧎', 'person_kneeling', ''],
  ['🧎‍➡️', 'person_kneeling_facing_right', ''],
  ['🏋️', 'person_lifting_weights', 'lifter'],
  ['🚵', 'person_mountain_biking', 'bike bicycle cyclist bicyclist'],
  ['🤾', 'person_playing_handball', ''],
  ['🤽', 'person_playing_water_polo', ''],
  ['🙎', 'person_pouting', 'gesture'],
  ['🙋', 'person_raising_hand', 'happy raised gesture'],
  ['🧑‍🦰', 'person_red_hair', 'adult gender neutral unspecified gender'],
  ['🚣', 'person_rowing_boat', 'rowboat'],
  ['🏃', 'person_running', 'marathon'],
  ['🏃‍➡️', 'person_running_facing_right', 'marathon'],
  ['🤷', 'person_shrugging', 'doubt ignorance indifference'],
  ['🧍', 'person_standing', ''],
  ['🏄', 'person_surfing', ''],
  ['🏊', 'person_swimming', ''],
  ['🛀', 'person_taking_bath', 'bathtub'],
  ['💁', 'person_tipping_hand', 'help sassy information'],
  ['🚶', 'person_walking', 'hike'],
  ['🚶‍➡️', 'person_walking_facing_right', 'hike'],
  ['👳', 'person_wearing_turban', ''],
  ['🧑‍🦳', 'person_white_hair', 'adult gender neutral unspecified gender'],
  ['🫅', 'person_with_crown', 'noble regal monarch royalty'],
  ['👰', 'person_with_veil', 'bride wedding'],
  ['🧑‍🦯', 'person_with_white_cane', 'blind accessibility'],
  ['🧑‍🦯‍➡️', 'person_with_white_cane_facing_right', 'blind accessibility'],
  ['🐈', 'pet', 'cat'],
  ['🧫', 'petri_dish', 'lab biology culture bacteria biologist'],
  ['🐦‍🔥', 'phoenix', 'fantasy rebirth firebird reincarnation'],
  ['🥥', 'pi_a_colada', 'palm coconut'],
  ['🪅', 'pi_ata', 'party celebration'],
  ['🛻', 'pick_up', 'truck pickup pickup truck'],
  ['🪧', 'picket', 'sign placard protest demonstration'],
  ['🥒', 'pickle', 'food cucumber vegetable'],
  ['🥧', 'pie', 'pastry filling'],
  ['🐷', 'pig_face', ''],
  ['🐽', 'pig_nose', 'face'],
  ['💩', 'pile_of_poo', 'dung face poop monster'],
  ['💊', 'pill', 'sick doctor medicine'],
  ['🧑‍✈️', 'pilot', 'plane'],
  ['📌', 'pin', 'pushpin'],
  ['🎍', 'pine_decoration', 'bamboo japanese celebration'],
  ['🍍', 'pineapple', 'fruit'],
  ['🏓', 'ping_pong', 'bat ball game paddle table tennis'],
  ['🩷', 'pink_heart', 'cute like love'],
  ['🏴‍☠️', 'pirate_flag', 'plunder treasure jolly roger'],
  ['🐟', 'pisces', 'fish zodiac'],
  ['🍕', 'pizza', 'slice cheese'],
  ['🛐', 'place_of_worship', 'religion'],
  ['▶️', 'play_button', 'arrow right triangle'],
  ['⏯️', 'play_or_pause_button', 'arrow right triangle'],
  ['🛝', 'playground_slide', 'theme park amusement park'],
  ['🐻‍❄️', 'polar_bear', 'white arctic'],
  ['🚓', 'police_car', 'patrol'],
  ['🚨', 'police_car_light', 'beacon revolving'],
  ['👮', 'police_officer', 'cop'],
  ['🐩', 'poodle', 'dog'],
  ['🎱', 'pool_8_ball', 'game eight billiard'],
  ['🍿', 'popcorn', ''],
  ['🏤', 'post_office', 'european'],
  ['📯', 'postal_horn', ''],
  ['📮', 'postbox', 'mail mailbox'],
  ['🍲', 'pot_of_food', 'stew'],
  ['🚰', 'potable_water', 'drinking'],
  ['🥔', 'potato', 'food vegetable'],
  ['🪴', 'potted_plant', 'grow house boring useless nurturing'],
  ['🍗', 'poultry_leg', 'bone chicken drumstick'],
  ['💷', 'pound_banknote', 'bill money currency'],
  ['🫗', 'pouring_liquid', 'drink empty glass spill'],
  ['😾', 'pouting_cat', 'face'],
  ['📿', 'prayer_beads', 'clothing necklace religion'],
  ['🫃', 'pregnant_man', 'full belly bloated'],
  ['🫄', 'pregnant_person', 'full belly bloated'],
  ['🤰', 'pregnant_woman', ''],
  ['🦋', 'pretty', 'insect butterfly'],
  ['🥨', 'pretzel', 'twisted'],
  ['🤴', 'prince', ''],
  ['🖨️', 'printer', 'computer'],
  ['🏆', 'prize', 'trophy'],
  ['🧾', 'proof', 'receipt evidence accounting bookkeeping'],
  ['📢', 'public_address', 'loud loudspeaker'],
  ['🧷', 'punk_rock', 'diaper safety pin'],
  ['🥺', 'puppy_eyes', 'mercy begging pleading face'],
  ['🟣', 'purple_circle', ''],
  ['💜', 'purple_heart', ''],
  ['🟪', 'purple_square', ''],
  ['🧩', 'puzzle_piece', 'clue jigsaw interlocking'],
  ['®️', 'r', 'registered'],
  ['🐰', 'rabbit_face', 'pet bunny'],
  ['🏎️', 'racing_car', ''],
  ['📻', 'radio', 'video'],
  ['🔘', 'radio_button', 'geometric'],
  ['☢️', 'radioactive', 'sign'],
  ['🚃', 'railway_car', 'tram train electric trolleybus'],
  ['🛤️', 'railway_track', 'train'],
  ['🌈', 'rainbow', ''],
  ['🏳️‍🌈', 'rainbow_flag', 'pride'],
  ['🤚', 'raised_back_of_hand', 'backhand'],
  ['✊', 'raised_fist', 'hand punch clenched'],
  ['✋', 'raised_hand', 'high 5 high five'],
  ['🙌', 'raising_hands', 'hooray raised gesture celebration'],
  ['♈', 'ram', 'aries zodiac'],
  ['🐀', 'rat', ''],
  ['🪇', 'rattle', 'music shake maracas instrument percussion'],
  ['🪒', 'razor', 'sharp shave'],
  ['🪃', 'rebound', 'boomerang repercussion'],
  ['⏺️', 'record_button', 'circle'],
  ['♻️', 'recycling_symbol', 'recycle'],
  ['🍎', 'red_apple', 'fruit'],
  ['🔴', 'red_circle', 'geometric'],
  ['❗', 'red_exclamation_mark', 'punctuation'],
  ['❤️', 'red_heart', ''],
  ['🏮', 'red_paper_lantern', 'bar light'],
  ['❓', 'red_question_mark', 'punctuation'],
  ['🟥', 'red_square', ''],
  ['🔻', 'red_triangle_pointed_down', 'geometric'],
  ['🔺', 'red_triangle_pointed_up', 'geometric'],
  ['🪸', 'reef', 'coral ocean'],
  ['😌', 'relieved_face', ''],
  ['🎗️', 'reminder_ribbon', 'celebration'],
  ['🔁', 'repeat_button', 'arrow clockwise'],
  ['🔂', 'repeat_single_button', 'once arrow clockwise'],
  ['⛑️', 'rescue_worker_s_helmet', 'aid hat face cross'],
  ['◀️', 'reverse_button', 'left arrow triangle'],
  ['💞', 'revolving_hearts', ''],
  ['🦏', 'rhinoceros', ''],
  ['🎀', 'ribbon', 'celebration'],
  ['🍙', 'rice_ball', 'japanese'],
  ['🍘', 'rice_cracker', ''],
  ['🗯️', 'right_anger_bubble', 'mad angry balloon'],
  ['➡️', 'right_arrow', 'east cardinal direction'],
  ['⤵️', 'right_arrow_curving_down', ''],
  ['↩️', 'right_arrow_curving_left', ''],
  ['⤴️', 'right_arrow_curving_up', ''],
  ['🤜', 'right_facing_fist', 'rightwards'],
  ['🫱', 'rightwards_hand', ''],
  ['🫸', 'rightwards_pushing_hand', 'stop wait refuse high five'],
  ['💍', 'ring', 'diamond'],
  ['🛟', 'ring_buoy', 'float rescue safety life saver life preserver'],
  ['🪐', 'ringed_planet', 'saturn saturnine'],
  ['🪳', 'roach', 'pest insect cockroach'],
  ['🛣️', 'road', 'highway motorway'],
  ['🍠', 'roasted_sweet_potato', ''],
  ['🤖', 'robot', 'face monster'],
  ['🚀', 'rocket', 'space'],
  ['🥐', 'roll', 'food bread french croissant breakfast'],
  ['🧻', 'roll_of_paper', 'paper towels toilet paper'],
  ['🗞️', 'rolled_up_newspaper', ''],
  ['🎢', 'roller_coaster', 'theme park amusement park'],
  ['🛼', 'roller_skate', ''],
  ['🤣', 'rolling_on_the_floor_laughing', 'face rofl rotfl'],
  ['🐓', 'rooster', 'bird'],
  ['🌹', 'rose', 'flower'],
  ['🏵️', 'rosette', 'plant'],
  ['📍', 'round_pushpin', ''],
  ['🏉', 'rugby_football', ''],
  ['🪜', 'rung', 'step climb ladder'],
  ['🎽', 'running_shirt', 'sash athletics'],
  ['👟', 'running_shoe', 'sneaker athletic clothing'],
  ['😥', 'sad_but_relieved_face', 'whew disappointed'],
  ['🦺', 'safety_vest', 'emergency'],
  ['🍶', 'sake', 'bar cup drink bottle beverage'],
  ['🧂', 'salt', 'shaker condiment'],
  ['🫡', 'saluting_face', 'ok yes sunny salute troops'],
  ['🥪', 'sandwich', 'bread'],
  ['🎅', 'santa_claus', 'father christmas celebration'],
  ['🥻', 'sari', 'dress clothing'],
  ['🎒', 'satchel', 'bag school backpack rucksack'],
  ['🛰️', 'satellite', 'space'],
  ['📡', 'satellite_antenna', 'dish'],
  ['🦕', 'sauropod', 'diplodocus brontosaurus brachiosaurus'],
  ['🎷', 'sax', 'music saxophone instrument'],
  ['🏫', 'school', 'building'],
  ['🦂', 'scorpio', 'zodiac scorpion'],
  ['♏', 'scorpius', 'zodiac scorpio scorpion'],
  ['🪛', 'screw', 'tool screwdriver'],
  ['📜', 'scroll', 'paper'],
  ['⛵', 'sea', 'boat yacht resort sailboat'],
  ['🦭', 'sea_lion', 'seal'],
  ['💺', 'seat', 'chair'],
  ['🙈', 'see_no_evil_monkey', 'face forbidden'],
  ['🌱', 'seedling', 'young'],
  ['🤳', 'selfie', 'phone camera'],
  ['🪝', 'selling_point', 'hook catch crook curve ensnare'],
  ['🐕‍🦺', 'service_dog', 'assistance accessibility'],
  ['🕖', 'seven_o_clock', '7 00 7:00'],
  ['🕢', 'seven_thirty', '7 7:30 clock'],
  ['🪡', 'sewing_needle', 'sutures stitches tailoring embroidery'],
  ['🫨', 'shaking_face', 'shock vibrate earthquake'],
  ['🥘', 'shallow_pan_of_food', 'paella casserole'],
  ['☘️', 'shamrock', 'plant'],
  ['🦈', 'shark', 'fish'],
  ['🍧', 'shaved_ice', 'sweet dessert'],
  ['🌾', 'sheaf_of_rice', 'ear grain'],
  ['🦐', 'shellfish', 'food small shrimp'],
  ['🛡️', 'shield', 'weapon'],
  ['⛩️', 'shinto_shrine', 'religion'],
  ['🌠', 'shooting_star', 'falling'],
  ['🛍️', 'shopping_bags', 'hotel'],
  ['🛒', 'shopping_cart', 'trolley'],
  ['🍰', 'shortcake', 'slice sweet pastry dessert'],
  ['🚿', 'shower', 'water'],
  ['🔀', 'shuffle_tracks_button', 'arrow crossed'],
  ['🤫', 'shushing_face', 'quiet'],
  ['🤘', 'sign_of_the_horns', 'hand finger rock on'],
  ['🪯', 'sikh', 'khanda religion'],
  ['🪑', 'sit', 'seat chair'],
  ['🕕', 'six_o_clock', '6 00 6:00'],
  ['🕡', 'six_thirty', '6 6:30 clock'],
  ['🦴', 'skeleton', 'bone'],
  ['⛷️', 'skier', 'snow'],
  ['🎿', 'skis', 'snow'],
  ['☠️', 'skull_and_crossbones', 'face death monster'],
  ['🦨', 'skunk', 'stink'],
  ['🛷', 'sled', 'sledge sleigh'],
  ['😴', 'sleeping_face', 'zzz good night'],
  ['😪', 'sleepy_face', 'good night'],
  ['🙁', 'slightly_frowning_face', ''],
  ['🙂', 'slightly_smiling_face', 'smile'],
  ['🥿', 'slip_on', 'slipper flat shoe ballet flat'],
  ['🎰', 'slot_machine', 'game'],
  ['🦝', 'sly', 'raccoon curious'],
  ['🛩️', 'small_airplane', 'aeroplane'],
  ['🤏', 'small_amount', 'pinching hand'],
  ['🔹', 'small_blue_diamond', 'geometric'],
  ['🔸', 'small_orange_diamond', 'geometric'],
  ['😻', 'smiling_cat_with_heart_eyes', 'face love smile'],
  ['☺️', 'smiling_face', 'smile relaxed outlined'],
  ['😇', 'smiling_face_with_halo', 'angel fantasy innocent'],
  ['😍', 'smiling_face_with_heart_eyes', 'love smile'],
  ['🥰', 'smiling_face_with_hearts', 'adore crush in love'],
  ['😈', 'smiling_face_with_horns', 'smile fantasy fairy tale'],
  ['🤗', 'smiling_face_with_open_hands', 'hug hugging'],
  ['😊', 'smiling_face_with_smiling_eyes', 'blush smile'],
  ['😎', 'smiling_face_with_sunglasses', 'cool bright'],
  ['🥲', 'smiling_face_with_tear', 'proud touched grateful relieved'],
  ['😏', 'smirking_face', ''],
  ['🐌', 'snail', ''],
  ['🐍', 'snake', 'bearer zodiac serpent ophiuchus'],
  ['🤧', 'sneezing_face', 'sneeze gesundheit'],
  ['🏔️', 'snow_capped_mountain', 'cold'],
  ['🏂', 'snowboard', 'ski snowboarder'],
  ['❄️', 'snowflake', 'cold'],
  ['☃️', 'snowman', 'cold'],
  ['⛄', 'snowman_without_snow', 'cold'],
  ['⚽', 'soccer_ball', 'football'],
  ['🧦', 'socks', 'stocking'],
  ['🍦', 'soft_ice_cream', 'sweet dessert icecream'],
  ['🥎', 'softball', 'glove underarm'],
  ['🔜', 'soon_arrow', ''],
  ['🆘', 'sos_button', 'help'],
  ['🐖', 'sow', 'pig'],
  ['♠️', 'spade_suit', 'card game'],
  ['🎇', 'sparkler', 'fireworks celebration'],
  ['✨', 'sparkles', '* star'],
  ['💖', 'sparkling_heart', 'excited sparkle'],
  ['🙊', 'speak_no_evil_monkey', 'face forbidden'],
  ['🔊', 'speaker_high_volume', 'loud'],
  ['🔈', 'speaker_low_volume', 'soft'],
  ['🔉', 'speaker_medium_volume', ''],
  ['🗣️', 'speaking_head', 'face silhouette'],
  ['💬', 'speech_balloon', 'comic bubble dialog'],
  ['🚤', 'speedboat', ''],
  ['🕷️', 'spider', 'insect'],
  ['🕸️', 'spider_web', ''],
  ['🦔', 'spiny', 'hedgehog'],
  ['🗓️', 'spiral_calendar', 'pad'],
  ['🗒️', 'spiral_notepad', ''],
  ['🐚', 'spiral_shell', ''],
  ['🧽', 'sponge', 'porous cleaning absorbing'],
  ['🧵', 'spool', 'thread needle sewing string'],
  ['🥄', 'spoon', 'tableware'],
  ['🚙', 'sport_utility_vehicle', 'recreational'],
  ['🏅', 'sports_medal', ''],
  ['🦒', 'spots', 'giraffe'],
  ['🐳', 'spouting_whale', 'face'],
  ['🕵️', 'spy', 'sleuth detective'],
  ['🪗', 'squeeze_box', 'accordion concertina'],
  ['🦑', 'squid', 'food molusc'],
  ['😝', 'squinting_face_with_tongue', 'eye taste horrible'],
  ['🏟️', 'stadium', ''],
  ['⭐', 'star', ''],
  ['☪️', 'star_and_crescent', 'islam muslim religion'],
  ['✡️', 'star_of_david', 'jew jewish religion'],
  ['🤩', 'star_struck', 'eyes face grinning'],
  ['🚉', 'station', 'train railway'],
  ['🗽', 'statue_of_liberty', ''],
  ['🚂', 'steam', 'train engine railway locomotive'],
  ['🍜', 'steaming_bowl', 'ramen noodle'],
  ['🩺', 'stethoscope', 'heart doctor medicine'],
  ['⏹️', 'stop_button', 'square'],
  ['🛑', 'stop_sign', 'octagonal'],
  ['⏱️', 'stopwatch', 'clock'],
  ['📏', 'straight_edge', 'ruler straight ruler'],
  ['🍓', 'strawberry', 'fruit'],
  ['🧑‍🎓', 'student', 'graduate'],
  ['🎙️', 'studio_microphone', 'music'],
  ['🥙', 'stuffed_flatbread', 'food gyro kebab falafel'],
  ['☀️', 'sun', 'rays sunny bright'],
  ['⛅', 'sun_behind_cloud', ''],
  ['🌥️', 'sun_behind_large_cloud', ''],
  ['🌦️', 'sun_behind_rain_cloud', ''],
  ['🌤️', 'sun_behind_small_cloud', ''],
  ['🌞', 'sun_with_face', 'bright'],
  ['🌻', 'sunflower', ''],
  ['🌅', 'sunrise', 'morning'],
  ['🌄', 'sunrise_over_mountains', 'morning'],
  ['🦸', 'superhero', 'good heroine superpower'],
  ['🦹', 'supervillain', 'evil criminal superpower'],
  ['🍣', 'sushi', ''],
  ['🚟', 'suspension_railway', ''],
  ['💦', 'sweat_droplets', 'comic splashing'],
  ['🫕', 'swiss', 'pot fondue cheese melted chocolate'],
  ['🕍', 'synagogue', 'jew jewish temple religion'],
  ['💉', 'syringe', 'shot sick needle medicine'],
  ['🦖', 't_rex', 'tyrannosaurus rex'],
  ['👕', 't_shirt', 'tshirt clothing'],
  ['🌮', 'taco', 'mexican'],
  ['🥡', 'takeout_box', 'oyster pail'],
  ['🦜', 'talk', 'bird parrot pirate'],
  ['🫔', 'tamale', 'mexican wrapped'],
  ['🎋', 'tanabata_tree', 'banner japanese celebration'],
  ['🍊', 'tangerine', 'fruit orange'],
  ['🚕', 'taxi', 'vehicle'],
  ['🧑‍🏫', 'teacher', 'lecturer professor instructor'],
  ['🍵', 'teacup_without_handle', 'drink beverage'],
  ['🫖', 'teapot', 'drink'],
  ['📆', 'tear_off_calendar', ''],
  ['🧸', 'teddy_bear', 'toy plush stuffed plaything'],
  ['☎️', 'telephone', ''],
  ['📞', 'telephone_receiver', ''],
  ['🔭', 'telescope', 'tool science'],
  ['📺', 'television', 'tv video'],
  ['🕙', 'ten_o_clock', '00 10 10:00'],
  ['🕥', 'ten_thirty', '10 10:30 clock'],
  ['🎾', 'tennis', 'ball racquet'],
  ['⛺', 'tent', 'camping'],
  ['🧪', 'test_tube', 'lab chemist science chemistry experiment'],
  ['🤔', 'thinking_face', ''],
  ['🩴', 'thong_sandal', 'zōri thongs sandals beach sandals thong sandals'],
  ['💭', 'thought_balloon', 'comic bubble'],
  ['🕒', 'three_o_clock', '3 00 3:00'],
  ['🕞', 'three_thirty', '3 3:30 clock'],
  ['👎', 'thumbs_down', ' 1 hand'],
  ['👍', 'thumbs_up', '+1 hand'],
  ['🎫', 'ticket', 'admission'],
  ['🐅', 'tiger', ''],
  ['🐯', 'tiger_face', ''],
  ['⏲️', 'timer_clock', ''],
  ['🛞', 'tire', 'turn wheel circle'],
  ['😫', 'tired_face', ''],
  ['🚽', 'toilet', ''],
  ['🗼', 'tokyo_tower', ''],
  ['🍅', 'tomato', 'fruit vegetable'],
  ['🦷', 'tooth', 'dentist'],
  ['🔝', 'top_arrow', 'up'],
  ['🎩', 'top_hat', 'tophat clothing'],
  ['🔦', 'torch', 'tool light electric flashlight'],
  ['🌪️', 'tornado', 'cloud whirlwind'],
  ['🖲️', 'trackball', 'computer'],
  ['🚜', 'tractor', 'vehicle'],
  ['™️', 'trade_mark', 'tm trademark'],
  ['🚆', 'train', 'railway'],
  ['🚊', 'tram', 'trolleybus'],
  ['🚋', 'tram_car', 'trolleybus'],
  ['🏳️‍⚧️', 'transgender_flag', 'pink white light blue'],
  ['⚧️', 'transgender_symbol', ''],
  ['🧳', 'travel', 'luggage packing'],
  ['🚩', 'triangular_flag', 'post'],
  ['📐', 'triangular_ruler', 'set triangle'],
  ['🔱', 'trident_emblem', 'ship tool anchor'],
  ['🧜‍♂️', 'triton', 'merman'],
  ['🚎', 'trolley', 'bus tram trolleybus'],
  ['🍹', 'tropical_drink', 'bar'],
  ['🐠', 'tropical_fish', ''],
  ['🎺', 'trumpet', 'music instrument'],
  ['🛺', 'tuk_tuk', 'auto rickshaw'],
  ['🌷', 'tulip', 'flower'],
  ['🥃', 'tumbler_glass', 'shot liquor whisky'],
  ['🦃', 'turkey', 'bird'],
  ['🐢', 'turtle', 'terrapin tortoise'],
  ['🦣', 'tusk', 'large woolly mammoth extinction'],
  ['🕛', 'twelve_o_clock', '00 12 12:00'],
  ['🕧', 'twelve_thirty', '12 12:30 clock'],
  ['♊', 'twins', 'gemini zodiac'],
  ['💕', 'two_hearts', 'love'],
  ['🐫', 'two_hump_camel', 'bactrian'],
  ['🕑', 'two_o_clock', '2 00 2:00'],
  ['🕝', 'two_thirty', '2 2:30 clock'],
  ['🦢', 'ugly_duckling', 'swan bird cygnet'],
  ['☂️', 'umbrella', 'rain clothing'],
  ['⛱️', 'umbrella_on_ground', 'sun rain'],
  ['☔', 'umbrella_with_rain_drops', 'clothing'],
  ['😒', 'unamused_face', 'unhappy'],
  ['🦄', 'unicorn', 'face'],
  ['🔓', 'unlock', 'open unlocked'],
  ['⬆️', 'up_arrow', 'north cardinal direction'],
  ['🆙', 'up_button', 'mark'],
  ['↕️', 'up_down_arrow', ''],
  ['↖️', 'up_left_arrow', 'direction northwest intercardinal'],
  ['↗️', 'up_right_arrow', 'direction northeast intercardinal'],
  ['🙃', 'upside_down_face', ''],
  ['🔼', 'upwards_button', 'arrow'],
  ['🧛', 'vampire', 'undead dracula'],
  ['🪣', 'vat', 'cask pail bucket'],
  ['🚦', 'vertical_traffic_light', 'signal'],
  ['📼', 'vhs', 'tape video videocassette'],
  ['📳', 'vibration_mode', 'cell phone mobile telephone'],
  ['🗜️', 'vice', 'tool clamp compress'],
  ['✌️', 'victory_hand', ''],
  ['📹', 'video_camera', ''],
  ['🎮', 'video_game', 'controller'],
  ['🎻', 'violin', 'music instrument'],
  ['👧', 'virgo', 'girl young zodiac'],
  ['🌋', 'volcano', 'eruption mountain'],
  ['🏐', 'volleyball', 'game'],
  ['🆚', 'vs_button', 'versus'],
  ['🖖', 'vulcan_salute', 'hand spock finger'],
  ['🧟', 'walking_dead', 'zombie undead'],
  ['🌘', 'waning_crescent_moon', ''],
  ['🌖', 'waning_gibbous_moon', ''],
  ['⚠️', 'warning', ''],
  ['🗑️', 'wastebasket', ''],
  ['⌚', 'watch', 'clock'],
  ['🐃', 'water_buffalo', ''],
  ['🚾', 'water_closet', 'wc toilet bathroom lavatory restroom'],
  ['🔫', 'water_pistol', 'gun tool weapon handgun revolver'],
  ['🌊', 'water_wave', 'ocean'],
  ['🍉', 'watermelon', 'fruit'],
  ['👋', 'waving_hand', 'wave'],
  ['〰️', 'wavy_dash', 'punctuation'],
  ['🌒', 'waxing_crescent_moon', ''],
  ['🌔', 'waxing_gibbous_moon', ''],
  ['🚻', 'wc', 'toilet restroom bathroom lavatory'],
  ['🙀', 'weary_cat', 'oh face surprised'],
  ['😩', 'weary_face', 'tired'],
  ['🌡️', 'weather', 'thermometer'],
  ['🐋', 'whale', ''],
  ['☸️', 'wheel_of_dharma', 'buddhist religion'],
  ['♿', 'wheelchair_symbol', 'access'],
  ['🦯', 'white_cane', 'blind accessibility'],
  ['⚪', 'white_circle', 'geometric'],
  ['❕', 'white_exclamation_mark', 'outlined punctuation'],
  ['🏳️', 'white_flag', 'waving'],
  ['💮', 'white_flower', ''],
  ['🤍', 'white_heart', ''],
  ['⬜', 'white_large_square', 'geometric'],
  ['◽', 'white_medium_small_square', 'geometric'],
  ['◻️', 'white_medium_square', 'geometric'],
  ['❔', 'white_question_mark', 'outlined punctuation'],
  ['▫️', 'white_small_square', 'geometric'],
  ['🔳', 'white_square_button', 'outlined geometric'],
  ['🛜', 'wi_fi', 'wifi network wireless computer internet'],
  ['🥦', 'wild_cabbage', 'broccoli'],
  ['🥀', 'wilted_flower', ''],
  ['🎐', 'wind_chime', 'bell celebration'],
  ['🌬️', 'wind_face', 'blow cloud'],
  ['🍷', 'wine_glass', 'bar drink beverage'],
  ['🪽', 'wing', 'bird flying angelic aviation mythology'],
  ['😉', 'winking_face', ''],
  ['😜', 'winking_face_with_tongue', 'eye joke'],
  ['🐺', 'wolf', 'face'],
  ['👫', 'woman_and_man_holding_hands', 'couple'],
  ['👩‍🎨', 'woman_artist', 'palette'],
  ['👩‍🚀', 'woman_astronaut', 'rocket'],
  ['👩‍🦲', 'woman_bald', 'adult'],
  ['🧔‍♀️', 'woman_beard', ''],
  ['🚴‍♀️', 'woman_biking', 'bicycle cyclist'],
  ['👱‍♀️', 'woman_blond_hair', 'blonde blond haired woman'],
  ['⛹️‍♀️', 'woman_bouncing_ball', ''],
  ['🙇‍♀️', 'woman_bowing', 'favor sorry apology gesture'],
  ['🤸‍♀️', 'woman_cartwheeling', 'gymnastics'],
  ['🧗‍♀️', 'woman_climbing', 'climber'],
  ['👷‍♀️', 'woman_construction_worker', ''],
  ['👩‍🍳', 'woman_cook', 'chef'],
  ['👩‍🦱', 'woman_curly_hair', 'adult'],
  ['💃', 'woman_dancing', 'dance'],
  ['🕵️‍♀️', 'woman_detective', 'spy sleuth'],
  ['🧝‍♀️', 'woman_elf', 'magical'],
  ['🤦‍♀️', 'woman_facepalming', 'disbelief exasperation'],
  ['👩‍🏭', 'woman_factory_worker', 'assembly industrial'],
  ['🧚‍♀️', 'woman_fairy', 'titania'],
  ['👩‍🌾', 'woman_farmer', 'rancher gardener'],
  ['👩‍🍼', 'woman_feeding_baby', 'nursing'],
  ['👩‍🚒', 'woman_firefighter', 'firetruck'],
  ['🙍‍♀️', 'woman_frowning', 'gesture'],
  ['🧞‍♀️', 'woman_genie', 'djinn'],
  ['🙅‍♀️', 'woman_gesturing_no', 'hand gesture forbidden prohibited'],
  ['🙆‍♀️', 'woman_gesturing_ok', 'hand gesture'],
  ['💇‍♀️', 'woman_getting_haircut', ''],
  ['💆‍♀️', 'woman_getting_massage', 'face'],
  ['🏌️‍♀️', 'woman_golfing', ''],
  ['💂‍♀️', 'woman_guard', ''],
  ['👩‍⚕️', 'woman_health_worker', 'nurse doctor therapist healthcare'],
  ['🧘‍♀️', 'woman_in_lotus_position', 'yoga meditation'],
  ['👩‍🦽', 'woman_in_manual_wheelchair', 'accessibility'],
  ['👩‍🦽‍➡️', 'woman_in_manual_wheelchair_facing_right', 'accessibility'],
  ['👩‍🦼', 'woman_in_motorized_wheelchair', 'accessibility'],
  ['👩‍🦼‍➡️', 'woman_in_motorized_wheelchair_facing_right', 'accessibility'],
  ['🧖‍♀️', 'woman_in_steamy_room', 'sauna steam room'],
  ['🤵‍♀️', 'woman_in_tuxedo', ''],
  ['👩‍⚖️', 'woman_judge', 'law scales justice'],
  ['🤹‍♀️', 'woman_juggling', 'multitask'],
  ['🧎‍♀️', 'woman_kneeling', ''],
  ['🧎‍♀️‍➡️', 'woman_kneeling_facing_right', ''],
  ['🏋️‍♀️', 'woman_lifting_weights', 'weight lifter'],
  ['🧙‍♀️', 'woman_mage', 'witch sorceress'],
  ['👩‍🔧', 'woman_mechanic', 'plumber electrician tradesperson'],
  ['🚵‍♀️', 'woman_mountain_biking', 'bike bicycle cyclist'],
  ['👩‍💼', 'woman_office_worker', 'manager business architect white collar'],
  ['👩‍✈️', 'woman_pilot', 'plane'],
  ['🤾‍♀️', 'woman_playing_handball', ''],
  ['🤽‍♀️', 'woman_playing_water_polo', ''],
  ['👮‍♀️', 'woman_police_officer', 'cop'],
  ['🙎‍♀️', 'woman_pouting', 'gesture'],
  ['🙋‍♀️', 'woman_raising_hand', 'gesture'],
  ['👩‍🦰', 'woman_red_hair', 'adult'],
  ['🚣‍♀️', 'woman_rowing_boat', 'rowboat'],
  ['🏃‍♀️', 'woman_running', 'racing marathon'],
  ['🏃‍♀️‍➡️', 'woman_running_facing_right', 'racing marathon'],
  ['👢', 'woman_s_boot', 'shoe clothing'],
  ['👚', 'woman_s_clothes', 'clothing'],
  ['👒', 'woman_s_hat', 'clothing'],
  ['👡', 'woman_s_sandal', 'shoe clothing'],
  ['👩‍🔬', 'woman_scientist', 'chemist engineer biologist physicist'],
  ['🤷‍♀️', 'woman_shrugging', 'doubt ignorance indifference'],
  ['👩‍🎤', 'woman_singer', 'rock star actor entertainer'],
  ['🧍‍♀️', 'woman_standing', ''],
  ['👩‍🎓', 'woman_student', 'graduate'],
  ['🦸‍♀️', 'woman_superhero', 'good heroine superpower'],
  ['🦹‍♀️', 'woman_supervillain', 'evil criminal superpower'],
  ['🏄‍♀️', 'woman_surfing', ''],
  ['🏊‍♀️', 'woman_swimming', ''],
  ['👩‍🏫', 'woman_teacher', 'lecturer professor instructor'],
  ['👩‍💻', 'woman_technologist', 'coder inventor software developer'],
  ['💁‍♀️', 'woman_tipping_hand', 'sassy'],
  ['🧛‍♀️', 'woman_vampire', 'undead'],
  ['🚶‍♀️', 'woman_walking', 'hike'],
  ['🚶‍♀️‍➡️', 'woman_walking_facing_right', 'hike'],
  ['👳‍♀️', 'woman_wearing_turban', ''],
  ['👩‍🦳', 'woman_white_hair', 'adult'],
  ['🧕', 'woman_with_headscarf', 'hijab tichel mantilla'],
  ['👰‍♀️', 'woman_with_veil', ''],
  ['👩‍🦯', 'woman_with_white_cane', 'blind accessibility'],
  ['👩‍🦯‍➡️', 'woman_with_white_cane_facing_right', 'blind accessibility'],
  ['🧟‍♀️', 'woman_zombie', 'undead walking dead'],
  ['👭', 'women_holding_hands', 'couple'],
  ['🚺', 'women_s_room', 'wc woman toilet bathroom lavatory restroom'],
  ['👯‍♀️', 'women_with_bunny_ears', 'dancer partying'],
  ['🤼‍♀️', 'women_wrestling', 'wrestle'],
  ['🦙', 'wool', 'llama alpaca vicuña guanaco'],
  ['🥴', 'woozy_face', 'dizzy tipsy wavy mouth intoxicated uneven eyes'],
  ['🗺️', 'world_map', ''],
  ['🪱', 'worm', 'annelid parasite earthworm'],
  ['😟', 'worried_face', ''],
  ['🌯', 'wrap', 'burrito mexican'],
  ['🎁', 'wrapped_gift', 'box present celebration'],
  ['🔧', 'wrench', 'tool spanner'],
  ['✍️', 'writing_hand', 'write'],
  ['🩻', 'x_ray', 'bones doctor medical skeleton'],
  ['🧶', 'yarn', 'ball knit crochet'],
  ['🥱', 'yawning_face', 'bored tired'],
  ['🟡', 'yellow_circle', ''],
  ['💛', 'yellow_heart', ''],
  ['🟨', 'yellow_square', ''],
  ['💴', 'yen_banknote', 'bill money currency'],
  ['☯️', 'yin_yang', 'tao taoist religion'],
  ['🪀', 'yo_yo', 'toy fluctuate'],
  ['👶', 'young', 'baby'],
  ['🤪', 'zany_face', 'eye goofy large small'],
  ['🦓', 'zebra', 'stripe'],
  ['🤐', 'zipper_mouth_face', ''],
  ['💤', 'zzz', 'comic sleep good night'],
];
